### ISSUE TITLE
Blaze campaign preview: Toolbar visible when it shouldn't be

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#10563]
When the Blaze creation is triggered and the product selector is shown, the campaign preview incorrectly shows the toolbar. It seems like there's a race condition in the way that the product selection result is handled by the `MyStoreFragment`, which is intermittently on the top of the backstack before the navigation shows `BlazeCampaignCreationPreviewFragment`.

[Screen_recording_20240117_180603.webm](https://github.com/woocommerce/woocommerce-android/assets/1522856/b93d3b17-b120-457a-9fe4-2e148fe0bbb6)

**Comment by JorgeMucientes** [comment]
### Extra Context

Copy pasting from prior investigation here: https://github.com/woocommerce/woocommerce-android/pull/10539:

When navigating to campaign preview screen from product selector there's an issue where the toolbar from `My Store tab` is shown on top of the toolbar from the campaign preview screen. See screen recording: 

https://github.com/woocommerce/woocommerce-android/assets/2663464/11f70a22-a855-49a0-a12d-ba1bfb3b1d46

The reason for this is how we handle navigation after selecting a product from the product selector. What happens internally in the above video is: 
1. When a product is selected from the product selector, the product selector is dismissed and the result is returned to the previous fragment, in this case `MyStoreFragment`
2. `MyStoreFragment` handles the result through `BlazeCampaignCreationDispatcher.attachFragment()` that triggers blaze campaign creation screen passing the selected productId. 

The problem is that between steps 1 and 2, `MyStoreFragment` is reloaded and `onViewCreated` called again. This triggers the animation to expand its toolbar. This animation is enqueued and  handled by `MainActivity.onFragmentViewCreated`. By the time the expand animation is run from MainActivity (the host activity for `MyStoreFragment` as well as `BlazeCampaignCreationPreviewFragment`), `MyStoreFragment` is not visible anymore and `BlazeCampaignCreationPreviewFragment` is, resulting in displaying the expanded toolbar for the campaign creation fragment.
