### ISSUE TITLE
Convert to using Android Navigation Components

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1061]
I met with a google engineer during Google I/O to talk about some of the issues we've been having with managing fragment states in this woo app. The grand takeaways from my session were:
1. Everyone has issues with managing the fragment lifecycle, even developers at Google.
2. This is precisely why the android team created the jetpack navigation components. 

So the recommendation was to switch our architecture over to using these new components now that they are in production.

**Comment by nbradbury** [comment]
I spent some time working with the Navigation Components, and my initial experiments were promising. We can do away with a lot of fragment lifecycle & save/restore code - and more importantly hopefully prevent a lot of fragment-related crashes - by migrating to them. The fact we can define actions, transitions, arguments, etc., through the navigation editor is also a big win, imo.

Unfortunately, in order to use the nav components we have to also migrate to AndroidX, which is no small task (especially considering the login library). However, that's something we're going to have to do anyway because Google won't be updating the support libraries beyond the current v28 release,

This may be something we want to work on at the same time as WPAndroid (open issue [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9209)) so everything is migrated at once.

**Comment by AmandaRiu** [comment]
Related #1134

**Comment by AmandaRiu** [comment]
Implemented in #1151
