### ISSUE TITLE
Orders to Fulfill card not translating

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1090]
**Describe the bug**
The "orders to fulfill" card in **My Store** is not translating

<img src="https://user-images.githubusercontent.com/5810477/58277867-f3f42000-7d57-11e9-9805-e1b565e7d3fe.png" width="300"/>

**Comment by anitaa1990** [comment]
Update: I found no translations for this text in strings.xml file.
`<string name="dashboard_fulfill_order_title_multiple">You have %1$d orders to fulfill</string>`

I added the following translated string to the corresponding `strings.xml` file:
`<string name="dashboard_fulfill_order_title_multiple">Tiene %1$d pedidos que cumplir</string>`and tried again and the text is translated correctly.

<img src="https://user-images.githubusercontent.com/22608780/58401371-3d57ae80-807b-11e9-8c1a-b82f2b903dfa.png" width="300"/>

I'm not sure if the text is not translated because it includes a formatting in it?

**Comment by AmandaRiu** [comment]
Looking at this a little closer it seems we are also missing translations for this string:
```
<string name="dashboard_fulfill_order_title_single">You have 1 order to fulfill</string>
```

Pinging @jkmassel to see if we can figure out how to proceed.

**Comment by AmandaRiu** [comment]
These translations exist in GlotPress, so we just need to run a script to pull them down. I've run that script and submitted a PR for the fix.

**Comment by anitaa1990** [comment]
Small update: There are 4 strings overall that are marked as fuzzy and not translated in almost all the languages. More details on this [here](https://i18n.wordpress.com/2019/05/27/fuzzy-strings-for-woocommerce-android-app/#comment-16432)
