### ISSUE TITLE
Remove the use of foreground service for image uploads

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#11307]
Google's [Permissions for Foreground Services policy](https://href.li/?https://notifications.google.com/g/p/ANiao5pz__Ry_rOG2-3WSqYq7AId7bdzGl4-MEyhQ0RThwVVKxgX7qIQLRPKZiWnQ96ODp3cTTBdep0r9PuARVYhsHJHXbi5fcO74rVjpNdXJTQSsE3ECufFI2bXjlQoZ4mpvYWYNxDMFk_-ToMW8FiEFMQtQ9L11PUbZ-ZRaIz50TL87uf5XCT0JOxYtZT20feQ6z3zoaolRM2fqJcMrdLUIy-fSBm15Lpxz7sA7Okgz4j0z5zeRGgZTBBKLXirlKSQpYVL) states that:

> **For apps targeting Android 14 and above, you must specify a valid foreground service type and permission for each foreground service used in your app**

Currently we use a foreground service to upload product images on devices running Android 13 and below. For Android 14 and above, we use the recommended approach by Google, which complies with their policies. Since we are still targeting Android 13 (API 33), we we’re fine but once we target API 34, we must remove the foreground service usage for any device Android version.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by irfano** [comment]
We are now targeting API 34 and we're still using foreground service for Android 13 and lower devices. I retested uploading an image when the app was in the background on an Android 13 device. The foreground service worked as expected.

> For apps targeting Android 14 and above, you must specify a valid foreground service type and permission for each foreground service used in your app

`For apps targeting Android 14 and above,` should refer to Android 14+ devices (not all devices after setting `targetSdk=34`).  Since we do not use foreground service for Android 14, no changes are necessary.
