### ISSUE TITLE
[Woo POS] Pass order data to totals screen after it being created

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11709]
Follow up to https://github.com/woocommerce/woocommerce-android/issues/11704

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
@samiuelson I reassigned this one to you since you have a draft PR in progress:
https://github.com/woocommerce/woocommerce-android/pull/11717

I'll work on displaying the totals view as [discussed](https://a8c.slack.com/archives/C06C3CZFHGD/p1718191720534879?thread_ts=1718116523.362199&cid=C06C3CZFHGD):
https://github.com/woocommerce/woocommerce-android/issues/11694

Thanks!
