### ISSUE TITLE
[Dynamic Dashboard] 19.0 Beta Feedbacks

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#11718]
Thanks to @itsmeichigo for these feedbacks.

```[tasklist]
### General
- [ ] "After updating the app, I don't see the suggestion for the new cards. I don't know how to make the suggestion show up."
- [x] In dark mode, update color of inactive checkmark circle in Customize screen to make it more visible @hafizrahman #11721
```

```[tasklist]
### Most recent reviews
- [x] There seems to be missing a divider on top of "View all reviews" button.
- [ ] The status "Unapproved" sounds a bit confusing. On iOS we use "Hold" as in not approved yet - but if this has always been the case for Android, please feel free to keep this.
```

```[tasklist]
### Most recent orders
- [x] The status labels in dark mode are hard to read. The titles should be dark since the background are light colors. @hafizrahman #11721
- [ ] Should the order status be sorted alphabetically to make it easier to browse?
```

```[tasklist]
### Most active coupons
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11741
```

```[tasklist]
### Stock
- [x] The items should be top-aligned so that the thumbnail's top align with the title even when it's too long. @hafizrahman
- [x] The items should be ordered by stock items from low to high (at least that's what 's done in iOS). @hafizrahman
- [x] When I lock the device then open the app again, I see that the stock card is reloaded. Is this necessary?
```

```[tasklist]
### Blaze
- [x] I tried to create a campaign with a product with an existing image and got an error about the image. I can create a campaign with this same product on iOS without error. @jorgemucientes
- [x] The campaigns are displayed with the text_snippet field. On iOS we display the site_name field and looks like the web does the same. @jorgemucientes
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Hey @itsmeichigo sharing some context about the beta feedback for `19.0`. We've addressed most issues. But there are some others I'm not sure we'll be addressing. Here's why:

- `The status "Unapproved" sounds a bit confusing. On iOS we use "Hold" as in not approved yet - but if this has always been the case for Android, please feel free to keep this.` About that. `Unapproved` is the same wording used in `wc-admin` for reviews. And you mentioned its the wording we've used for reviews in Android since the feature was added:

![Screenshot 2024-06-18 at 16 57 04](https://github.com/woocommerce/woocommerce-android/assets/2663464/9841e6d5-b9c7-4aaf-930c-0aff4f6bc01c)

- `The status "Unapproved" sounds a bit confusing. On iOS, we use "Hold" as in not approved yet - but if this has always been the case for Android, please feel free to keep this.`Unsure alphabetical order is useful here. The list of statuses is really short. Also, with similar reasoning as above, we follow the same order in which order statuses are displayed in `wc-admin`, which should be an order the user is familiar with.

![Screenshot 2024-06-18 at 16 39 15](https://github.com/woocommerce/woocommerce-android/assets/2663464/aa73cbd9-2d7f-4e86-b644-4950aabbf2f7)

- Created an issue for this one: https://github.com/woocommerce/woocommerce-android/issues/11741 . However I'll keep it as low priority because there's no straightforward implementation to support storing custom ranges per site. The amount of work required to support this vs the benefits the user will get doesn't seem like worth prioritising now. 


Let me know if you disagree with any of those points and think we should address them 🙂

**Comment by JorgeMucientes** [comment]
Also, one question about this one @itsmeichigo 

> "After updating the app, I don't see the suggestion for the new cards. I don't know how to make the suggestion show up."

I've been trying to reproduce that, but I can see the badge displayed correctly. 

https://github.com/woocommerce/woocommerce-android/assets/2663464/26d71ef3-f750-436c-8a64-420a7070c51f

How did you tested this? Note that if you do a clean installed, the badge and the card are not displayed. This are only displayed upon updating the app from an older version.
