### ISSUE TITLE
[Woo POS] M2: Disable "Exit POS" button during payment flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11980]

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
I haven't checked that, but I think we may not need it, as payment flow is hooked to the lifecycle of the dialog and gets canceled automatically. That has to be checked though

**Comment by AnirudhBhat** [comment]
Since the payment flow dialog doesn't allow any touch outside of the dialog, the `Exit POS` button won't be clickable as long as the payment flow dialog is on the screen. 

https://github.com/user-attachments/assets/d1241cf6-18fa-42da-8fba-d9d5cc781d9c

With that said, With the new M2 designs, the Exit POS button has been moved inside an Overflow Menu (three dots icon). Additionally, the payment flow has been redesigned and no longer appears in a dialog. Disabling the `Exit POS` button seems more relevant with the new design. 

p1721060894623919/1720798863.793069-slack-C070SJRA8DP

I suggest we do this when we are tackling the M2 designs. WDYT?

**Comment by kidinov** [comment]
@AnirudhBhat 👋

> Additionally, the payment flow has been redesigned and no longer appears in a dialog

On Android, it looks like we keep the reuse of the IPP flow, so I guess this ticket is not really relevant, at least for M2

**Comment by AnirudhBhat** [comment]
>On Android, it looks like we keep the reuse of the IPP flow

In that case, I'll go ahead and close the issue. Thank you!
