### ISSUE TITLE
[Woo POS] Wrong color used for the cross on "why can't I see my products" dialog

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12221]
![Image](https://github.com/user-attachments/assets/5199aee7-e9f5-4f97-bbad-8e15bc6770f1)

Notice that different color used for the cross compared to the banner itself

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by kidinov** [comment]
@AnirudhBhat 👋 

Could you please take a look into that? 

Also, I noticed that we save the dialog state inside of compose, instead of saving the whole state of the screen in VM and to have one source of truth. 

Another questional part is that we have the state constructed in compose for some reason too:

```
        val currentState = state as? ProductsInfoDialog.Visible ?: ProductsInfoDialog.Visible(
            header = R.string.woopos_dialog_products_info_heading,
            primaryMessage = R.string.woopos_dialog_products_info_primary_message,
            secondaryMessage = R.string.woopos_dialog_products_info_secondary_message,
            primaryButton = ProductsInfoDialog.Visible.PrimaryButton(
                label = R.string.woopos_dialog_products_info_button_label
            )
        )
```

There is also `BoxOverlay` which doesn't wrap anything and `onClick` that  also doesn't do anything

**Comment by AnirudhBhat** [comment]
Thanks for creating ticket!

Since there were no Android-specific designs for this UI, I referred to the iOS designs and I think I chose colours that matched those. I'll also adjust the cross icon to look similar to the Product Info banner that appears at the top of the product list.

>Also, I noticed that we save the dialog state inside of compose, instead of saving the whole state of the screen in VM and to have one source of truth.

That's correct. We avoided storing the entire dialog UI state across process death by only saving a boolean value that allows us to recreate the dialog when needed. While this could have been managed in the ViewModel, considering that this UI is temporary and will be removed soon, I'm questioning whether it's worth the effort to refactor it since the current approach is already functional.

>Another questional part is that we have the state constructed in compose for some reason too:

Yes. This is done to support state restoration across process death

>There is also BoxOverlay which doesn't wrap anything and onClick that also doesn't do anything

That's correct. If you observe, the products info dialog is not really a compose dialog. Instead, it's a compose view that mimics dialog. The reason for not using compose dialog here are
1. Since compose dialog's aren't like any other plain compose views (They don't have modifier parameter!!). It proved hard to animate as per the design
2. It was challenging to make a Compose dialog match the design, which requires the dialog to take up most of the screen.

Since it's not a real dialog, we needed a way to intercept and ignore clicks outside the view, just like a traditional dialog would.

**Comment by kidinov** [comment]
@AnirudhBhat 

> considering that this UI is temporary and will be removed soon

Why do you think so? I mean, all is temporary eventually, but I think we should still follow some approaches in terms of the code to keep it maintainable. 

> Yes. This is done to support state restoration across process death

The state should be stored in the VM using the saved instance state, not in compose, as we don't want to have a source of truth in multiple places

> That's correct. If you observe, the products info dialog is not really a compose dialog. Instead, it's a compose view that mimics dialog. 

I am not sure how this is connected to the fact that the box doesn't wrap anything and on click doesn't do anything. Please check `WooPosFloatingToolbar` where the same is implemented, and the box is wrapping the UI and on click does the  work

**Comment by AnirudhBhat** [comment]
@kidinov I've refactored as per the suggestion here: https://github.com/woocommerce/woocommerce-android/pull/12293

Let me know what you think of it.
