### ISSUE TITLE
[Woo POS] We end up in inconsistent state after failed payments flow

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#12342]
To reproduce:
* Start the payment flow with amount that ends in the error with contact support button (55cents)
* When an error displayed click on contact support button
* Come back
* Notice that we show products and cart in the checkout state

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kidinov** [comment]
Can not reproduce it anymore:
* Can be some race condition
* Maybe some changes on the trunk that fixed that

I will keep it open for now

**Comment by backwardstruck** [comment]
> Can not reproduce it anymore:
> 
> * Can be some race condition
> * Maybe some changes on the trunk that fixed that
> 
> I will keep it open for now

I was able to reproduce and I've seen this issue before:
![Screenshot_20240821_164342](https://github.com/user-attachments/assets/b4c797ef-7cfd-40c7-85f9-3ee9abe11497)

![Screenshot_20240821_164357](https://github.com/user-attachments/assets/bb75381f-0a0c-4108-85c9-3c2f8c7a8e42)


![Screenshot_20240821_164432](https://github.com/user-attachments/assets/518a65cb-61db-4818-867b-f5be4631d0d6)

**Comment by backwardstruck** [comment]
It definitely doesn't happen all the time so probably a race condition as you suggested @kidinov

Seems to happen most often if you WAIT while on the support screen for at least 15 seconds before returning. As if there is some process ongoing that cases a different state when you go back to the checkout screen.

**Comment by backwardstruck** [comment]
Turns out this doesn't require tapping on Contact support. If you background the app/lock the screen after 15 seconds from when the payment fails, then come back, it ends up in a similar broken state. So it must have to do with a task that finishes during those 15 seconds while the totals screen is in the background:

![Screenshot_20240822_152305](https://github.com/user-attachments/assets/e4033b12-a414-4b5c-b5fe-c6b187e2873c)
