### ISSUE TITLE
where we can place firebase server key on the woocommerce website?

### ISSUE THREAD

**Issue by ArslanKathia** [woocommerce/woocommerce-android#1429]
I have created the project on the firebase account and change the all thing related to firebase in the app but i am not getting the notification. i think issue is the server key. i just want to know that where we place the server key of firebase to get the notification when new order comes
or using any third party plugin to achieve this!

**Comment by AmandaRiu** [comment]
You can follow the instructions [here](https://firebase.google.com/docs/android/setup) for how to setup firebase in the app. You'd need to change the application ID of course because the one we use will no longer work for your own firebase messaging service. Then download your `google-services.json` file from google and place it in the same directory as `WooCommerce/google-services.json-example`. We are a very small team of developers and are not properly staffed to troubleshoot other developers setup so beyond the information provided above we cannot provide debugging and help troubleshooting.
