### ISSUE TITLE
Broken Tests: ProductDetailNavigationTest

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1451]
Most of the tests in the `ProductDetailNavigationTest` class are failing. It _looks_ like it may be related to the loading skeleton since most of the test failures are due to `androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching` type errors and it's usually when the product detail view is still loading.

**Comment by AmandaRiu** [comment]
cc: @nbradbury in case you want to grab this one since you worked on this feature and are most familiar with this part of the code.

**Comment by nbradbury** [comment]
Sorry @AmandaRiu - looks like I missed your ping on this! Looking at it now.

**Comment by nbradbury** [comment]
Hmm, looks like the situation has changed since this issue was filed. Most of the tests result in "Failing with "androidx.test.espresso.PerformException: Error performing 'single click - At Coordinates..."

This is due to animations not being disabled - see https://developer.android.com/training/testing/espresso/setup#set-up-environment

Once that's addressed, there are two other problems:

* We're trying to mock classes that are declared as final (see #1679)
* There's a problem with the currency formatter (see below)

```
E/WordPress-UTILS: Error finding valid currency symbol for currency code [] in locale [en_US]
    java.lang.IllegalArgumentException: The input currency code is not 3-letter alphabetic code.
        at android.icu.util.Currency.getInstance(Currency.java:303)
        at java.util.Currency.getInstance(Currency.java:96)
        at org.wordpress.android.fluxc.utils.WCCurrencyUtils.getLocalizedCurrencySymbolForCode(WCCurrencyUtils.kt:45)
        at org.wordpress.android.fluxc.store.WooCommerceStore.formatCurrencyForDisplay(WooCommerceStore.kt:170)
        at com.woocommerce.android.util.CurrencyFormatter.formatCurrency(CurrencyFormatter.kt:49)
```

@0nko As with #1679, I'm going to ask for your help here as you have a much better understanding of those two items.
