### ISSUE TITLE
Add a toggle for refund notification

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#1545]
The refund summary should contain a toggle that lets the user decide whether a customer should get an email about a refund.

![image](https://user-images.githubusercontent.com/1522856/68612538-0a846400-04bd-11ea-8d19-08bef806996d.png)

**Comment by joshbetz** [comment]
Am I correct that the API request here is to add a field to `POST /wc/v3/orders/723/refunds` to control whether an email is sent?

**Comment by anitaa1990** [comment]
> Am I correct that the API request here is to add a field to POST /wc/v3/orders/723/refunds to control whether an email is sent?

Yup, that is right 👍

**Comment by coreymckrill** [comment]
Is this based on user requests, or just the design mockups (or maybe both)?

Currently it looks like email notifications for refunds are configured in WooCommerce settings, and thus are applied to all refunds, rather than on a case-by-case basis. So adding this functionality to the API would also potentially require changing how the emails work at the system level. I also just wonder what the use case would be for _not_ sending an email notification when issuing a refund...

**Comment by rossanafmenezes** [comment]
Doing some clean-up. I will close this issue for now and if we decide this should be implemented in the future we can re-open. p1724170513224029-slack-C6H8C3G23
