### ISSUE TITLE
Dark Mode: Update status bar color

### ISSUE THREAD

**Issue by Garance91540** [woocommerce/woocommerce-android#1945]
The top nav bar background should also be the same as the status bar (Background: Elevation Overlay 04dp) on Dark Mode (similarly to how we implemented it on Light Mode) for all screens. 

<img width="714" alt="Screen Shot 2020-02-05 at 11 45 41 AM" src="https://user-images.githubusercontent.com/28450084/74523431-53fda880-4f1d-11ea-99bf-2a1d426bc2a6.png">

Some screens (Settings, Pick Store, Privacy Settings) display a nav bar without a background color on dark mode. It should be “Elevation overlay/04dp”

<img width="695" alt="Screen Shot 2020-02-05 at 11 45 23 AM" src="https://user-images.githubusercontent.com/28450084/74523468-6677e200-4f1d-11ea-9915-c255dde30ee7.png">

**Comment by AmandaRiu** [comment]
@Garance91540 

> The top nav bar background should also be the same as the status bar (Background: Elevation Overlay 04dp) on Dark Mode (similarly to how we implemented it on Light Mode) for all screens.

The status bar elevation is not something we have control over. We can set the color (which is why it's black), but we can't set the elevation (which is why its not the light color). 

> Some screens (Settings, Pick Store, Privacy Settings) display a nav bar without a background color on dark mode. It should be “Elevation overlay/04dp”

I've verified as of the latest build that all screens except for the store picker have elevation properly set. The Site picker is different because it's a shared screen with login so I those changes will be handled with login. 

<img width="1061" alt="Screen Shot 2020-02-17 at 6 04 20 PM" src="https://user-images.githubusercontent.com/5810477/74695094-f1700b00-51af-11ea-9cbb-649dbb2a391a.png">

**Comment by Garance91540** [comment]
> The status bar elevation is not something we have control over. We can set the color (which is why it's black), but we can't set the elevation (which is why its not the light color).

Thanks for the explanation, it makes sense! In this case, is it possible to update the status bar color to #272727?

**Comment by AmandaRiu** [comment]
@Garance91540 that's a really good idea...and yup, that worked. I'll open a PR for it 👍
