### ISSUE TITLE
API 21 - app unresponsive when switching between dark/light modes

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1972]
While testing this[ PR](https://github.com/woocommerce/woocommerce-android/pull/1963), I noticed that when I change the theme from `Light` to `Dark` or vice versa in emulator API 21, the screen hangs and is unresponsive. Once after closing the app and opening it again, the changes are visible. 

<img width="300" src="https://user-images.githubusercontent.com/22608780/75005217-ae55b680-5493-11ea-8360-036d53b517b9.gif">

**Comment by AmandaRiu** [comment]
This is a known issue for API 21 - 23. See Google IssueTracker ticket [here.](https://issuetracker.google.com/issues/131851825). I updated the appcompat dependency to `1.2.0-alpha03` as this issue is supposed to be fixed in that version and now the issue has just changed. The app no longer crashes, but the theme change will not be applied until the app is manually killed and restarted. Left a comment on the issue referenced above.

**Comment by AmandaRiu** [comment]
Per the latest update in the Google IssueTracker ticket, this should be fixed in appcompat version 1.2.0 (currently in beta). Will followup in a month to see if it has been released.
