### ISSUE TITLE
Products sometimes disappear

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#2097]
**Describe the bug**
While navigating the app, sometimes products will be downloaded, but then when navigating to the "Products" screen, the products will disappear after a moment – they'll be there, then suddenly are removed.

This is most noticeable while trying to generate screenshots.

**To Reproduce**
This reproduction comes from a screenshot test run. When running the screenshots test, it always comes up at least once (in 16 runs).

![disappearing-products](https://user-images.githubusercontent.com/1123407/77219478-c739a200-6afb-11ea-9c3c-cb5f90a81f1a.gif)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [] I can reproduce this bug consistently using the steps above.

**Comment by nbradbury** [comment]
Notes for myself: Chances are the bug is in the load more logic. Looking at the GIF I can see the "load more" progress bar at the bottom, but the load more action shouldn't be kicking in with so few products. 

<img width="436" alt="Screen Shot 2020-04-06 at 12 44 47 PM" src="https://user-images.githubusercontent.com/3903757/78583463-dfe8ce00-7804-11ea-865b-4f0aeb056a06.png">

**Comment by nbradbury** [comment]
I found a way to more reliably reproduce this, but it's not very consistent.

1. Tap a product in the product list to open product detail
2. Minimize the app
3. Restore it
4. Return to the product list
