### ISSUE TITLE
Products: Toggling a product setting twice saves the setting change even if I discard changes

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2132]
**Describe the bug**

If I toggle a product setting twice (i.e. on and then off, or off and then on, so the setting appears the same as when I opened the settings) and then discard my changes, the setting is saved as if I had only toggled it once. I noticed this for settings like:

* Price > Schedule sale
* Inventory > Manage stock
* Inventory > Limit one per order

**To Reproduce**

1. Go to app Settings > Beta features > enable Products.
2. Go to the products tab.
3. Select a product to open the product details.
4. Make an edit to the product (for example, change the product title).
4. Open the Inventory section.
5. Assuming the "Manage stock" setting is currently off: Toggle the Manage stock setting on.
6. Toggle the Manage stock setting off again.
7. Tap the back button in the top left.
8. Notice a prompt appears with options to keep editing or discard changes. Select "Discard."
9. Open the Inventory section again and notice that the "Manage stock" setting is now on.

**Screenshots**

Screencast: https://cloudup.com/cVo8DZPPYra

**Expected behavior**

When I make a change to product settings and then immediately revert the change, I don't expect a discard changes prompt (since I've left the settings in the same state they were in before). However, I especially don't expect that when I discard changes, any changes I made in that session will be saved!

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 3.9-rc-1

**Comment by rachelmcr** [comment]
I just updated the steps to reproduce with a step I was missing before (step 4) — that should make this issue reproducible.

**Comment by nbradbury** [comment]
The problem is due to checking if there are _any_ changes to the product when the back button is pressed. We should only be checking for changes made in that specific fragment.

**Comment by nbradbury** [comment]
@anitaa1990 I have a branch [here](https://github.com/woocommerce/woocommerce-android/compare/issue/2132-product-settings-toggle) with a potential fix, but it's not very elegant. You're more familiar with this code than I am, so could you take a look and see if there's a better solution?

My solution was to retain a separate copy of the product when a detail fragment is shown, and use that for comparison when the back button is pressed. It feels like we shouldn't have to do this, though, since we're already storing three separate copies of the product.

**Comment by anitaa1990** [comment]
@nbradbury, the changes look good! I  believe the `productBeforeEnteringFragment` is doing pretty much the same thing as `cachedProduct` except it is updated in the `BaseProductFragment` as opposed to `cachedProduct` which gets updated in a whole bunch of places inside the `ViewModel`.  

Your solution works better and removes a bunch the complexity of checking `product` vs `cachedProduct` in a number of places. I removed the `cachedProduct` from the code and tested a bit and it looks like this also fixes a couple of bugs involving discard dialog ( #1998 and #2126 and this one). cc @0nko since you were working on #1998 

I'd remove the `cachedProduct` from this [branch](https://github.com/woocommerce/woocommerce-android/compare/issue/2132-product-settings-toggle) and open a PR. Thanks so much for working on this!!
