### ISSUE TITLE
Product M2 release: purchase note

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2272]
The product settings screen should offer the ability to edit the purchase note.

<img width="188" alt="Screenshot 2020-03-13 at 12 21 53 PM" src="https://user-images.githubusercontent.com/22608780/76596912-4d1a8380-6525-11ea-8825-1b9b55d56c40.png">

<img width="188" alt="Screen Shot 2020-04-17 at 4 12 01 PM" src="https://user-images.githubusercontent.com/3903757/79610256-36d48a00-80c6-11ea-8350-86459955be21.png">

**Comment by anitaa1990** [comment]
Hey @nbradbury an issue for this had already been added to the  M2 release and an [issue](https://github.com/woocommerce/woocommerce-android/issues/2229) has already been filed by @pmusolino and added to the [Add/Edit Products release 2](https://github.com/woocommerce/woocommerce-android/projects/9) kanban board. Since you had already opened and started work on this issue I'll close #2229

**Comment by nbradbury** [comment]
Closed via #2277
