### ISSUE TITLE
Remove isAddEditProductRelease1Enabled

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#2297]
Now that simple editing has shipped, we can remove `isAddEditProductRelease1Enabled` from the product detail  fragment. This will be done as part of the product settings work to avoid conflicts.

**Comment by anitaa1990** [comment]
@nbradbury apologies that I'm just not getting to this issue but I seem to recall that we had removed the `FeatureFlag` for M1 release. The reason `isAddEditProductRelease1Enabled` is still around is because we had discussed enabling editing only for SIMPLE products for M1 release. For all the other products types, I seem to recall M3 being the release where we allow users to change the product type. Maybe wait till M3 to remove this?

**Comment by nbradbury** [comment]
> Maybe wait till M3 to remove this?

👍

**Comment by anitaa1990** [comment]
Closed via #2603
