### ISSUE TITLE
Refunds detail: Incorrect tax and shipping text displayed when viewing refund summary

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2304]
After testing a refund, I am seeing this incorrect text that is displayed in the refund detail screen. 

<img src="https://user-images.githubusercontent.com/22608780/80079611-24e36300-856e-11ea-9208-98712d1a93f7.png" width="300"/>

#### To reproduce:
I tried to refund a single product (with 0 amount) from a multi product order.

<img src="https://user-images.githubusercontent.com/22608780/80079765-565c2e80-856e-11ea-953b-7e5d3a6dd452.gif" width="300"/>

**Comment by rachelmcr** [comment]
I noticed that incorrect text appears in two places:

* Refunded product list (as in your screenshot above)
* Refund detail screen (under Order details > Payment section > tap on "Refunded" payment cell)

This was previously fixed in both places in https://github.com/woocommerce/woocommerce-android/pull/2006 so we should also look at what tests are needed to ensure this regression doesn't happen again.

**Comment by anitaa1990** [comment]
Closed by @0nko via #2565
