### ISSUE TITLE
Support: Email field length ("0/50") in support email dialog never changes

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2306]
**Describe the bug**

When I go to Help & Support > Contact email, a dialog appears where I can enter my email address. Under the email field, it looks like it's supposed to count the number of characters in my email address. However, it always says `0 / 50` — the number never updates while I'm typing or after I finish typing my email in that field.

**To Reproduce**

1. Go to Help (during login) or Help & Support (after login).
2. Select "Contact email."
3. Notice that a "Please enter your email address" dialog appears with `0 / 50` under the Email field.
4. Enter your email address in the email field. Notice the number `0 / 50` doesn't change.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/80096963-60783000-8562-11ea-9d43-821d70caa9fc.png" width="50%">

**Expected behavior**

I expect the number `0` to update with the number of characters I type in the Email field.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 4.1-rc-1

**Comment by AmandaRiu** [comment]
This bug is happening because the "Name" field is also a part of this dialog but is currently hidden, but we're still seeing the "max count" counter from _that_ field. The reason for this is because the edit text box for "Name" is inside a `TextInputLayout` with the counter enabled, but the code logic only hides the `EditText` child.
