### ISSUE TITLE
SelectedSite.get() was accessed before being initialized

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#2312]
Sentry issue: [WOOCOMMERCE-ANDROID-GT](https://sentry.io/share/issue/756fb41a674f463aa4bb56269cd5b3f9/)

```
IllegalStateException
SelectedSite.get() was accessed before being initialized - siteId -1.
Consider calling selectedSite.exists() to ensure site exists prior to calling selectedSite.get().
```

**Comment by AmandaRiu** [comment]
This is an issue caused a bunch of logic in `OrderDetailPresenter`  implemented using kotlin coroutines running in the `GlobalScope`  - which means they will run as long as the application is running, and there is nothing in place to cancel these coroutines since they are scoped to the application, and as long as they are running, the  `OrderDetailPresenter`  that is awaiting the results cannot be garbage collected. So what’s happening is:

1. [Request to fetch order](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L139)
2. OnOrderChanged() called with the result [where a block is defined](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L376) inside a `GlobalScope` [that calls](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L379) `fetchRefunds(…)` then `awaitRefunds()` which pauses execution of the rest of the block. 
3. The request is sent to [fetch refunds from the API](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L259) (also inside a `GlobalScope` block
4. The user logs out of the app.
5. The response to the refunds fetch returns and the block from step 2 in onOrderChanged() resumes. 
6. The `orderView` would be null so the next few lines would be skipped, until [we hit the line](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L383) to  `loadOrderNotes()`. Note that `orderModel` wouldn’t be null because it was set inside that same `GlobalScope` block in the  `onOrderChanged()` method.
7. [Call the method to request order notes from the API](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L177)
8. [And this is where we crash](https://github.com/woocommerce/woocommerce-android/blob/58c2085d1c48513f0bb0645e6b96d8a5a7fd065c/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/OrderDetailPresenter.kt#L499) because `selectedSite` would not be set due to the logout. 

I proved this theory out by putting a delay inside the `fetchRefunds()` `GlobalScope` block and then logged out. As soon as the delay expired the app crashed due to `selectedSite` not being initialized.

**Comment by anitaa1990** [comment]
Nice sleuthing @AmandaRiu! I wasn't able to reproduce the crash as such but since using `GlobalScope` is not recommended, I replaced that with  with scopes specific to the Order detail class. Since I wasn't able to reproduce the crash as such would you mind [taking a look at the fix and letting me know if the crash is fixed](https://github.com/woocommerce/woocommerce-android/compare/issue/2312-global-scope-crash-fix?expand=1)? Thanks so much ❤️
