### ISSUE TITLE
Top Performers v4: App does not match site

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2451]
Top Performers in the app does not match the top performers in the store WooCommerce Dashboard:

## App
Range: This Month
<img src="https://user-images.githubusercontent.com/5810477/82363108-9e823b80-99ca-11ea-9a93-daa8dd633e96.jpg" width="330"/>

## Store
Range: Month to Date
![Screen Shot 2020-05-19 at 12 17 55 PM](https://user-images.githubusercontent.com/5810477/82363293-d7221500-99ca-11ea-85cb-2ec957c60619.png)
![Screen Shot 2020-05-19 at 12 18 01 PM](https://user-images.githubusercontent.com/5810477/82363301-d8534200-99ca-11ea-8112-684c75b51573.png)

Also pulled a report for "Sunglasses" and only 1 was sold during the time period in question:

![Screen Shot 2020-05-19 at 12 19 13 PM](https://user-images.githubusercontent.com/5810477/82363405-0173d280-99cb-11ea-97ac-3c37055429b8.png)

WooCommerce Plugin v4.2.0-beta.1
WCadmin plugin: no
Pixel 2 - Android 10
WCAndroid 4.3-rc-1

**Comment by anitaa1990** [comment]
Hey @AmandaRiu, thanks for filling the issue! 

We don't actually use the `v4-analytics` API from WooCommerce-Admin plugin in the app. At the moment, we are using the `/wpcom/v2/sites/{{site_id}}/stats/top-earners/?unit=day&date=2020-05-20&limit=3&_locale=en_US ` API. I think the discrepancy might be because of that. 

There has been some discussion on updating the top earners endpoint to the new `v4-analytics` API but no definite ETA has been finalised as far as I know.

**Comment by AmandaRiu** [comment]
Thanks @anitaa1990!

**Comment by anitaa1990** [comment]
This should now be fixed with #2676  as long as the user is using WC 4.0 or greater. The previous top performers stats data were taken from WPCOM + Jetpack sync. The new leaderboard stats, to be released on 4.9, uses WCAdmin's API so the data should identically match now.
