### ISSUE TITLE
Change order status from main activity or orderlistfragment

### ISSUE THREAD

**Issue by cfranc3sc0s92** [woocommerce/woocommerce-android#2522]
Hi guys. I must to create a button in Orderlistfragment that change an order status.
I found WcOrdermodel of order that i need to edit but in orderlistfragment i can't use updatestatus.
Can help me? thanks

**Comment by AmandaRiu** [comment]
Hi @cfranc3sc0s92 we do not officially offer dev support since we are still a very small team (see our [contributing readme](https://github.com/woocommerce/woocommerce-android/blob/develop/CONTRIBUTING.md)). We do already have a way to update the status of an order in the order detail view (the pencil icon) so you can take a look at that code as a reference.
