### ISSUE TITLE
Make v4 stats the default

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#2539]
1. If we know for sure the new stats endpoint is available, then default to the new stats UI instead of displaying a banner message.
2. Remove the beta feature option for using the improved stats since it will be enabled by default.
3. ~Site does not have v4 wc-analytics namespace available OR Woo version is less than 4.0 - inform user that old stats will eventually go away, upgrade to 4.0 or install WCAdmin.~ This was already [added in this PR](https://github.com/woocommerce/woocommerce-android/pull/2127)
4. Update the date in the message shown in the image below to September 1, 2020.

<img width="541" src="https://user-images.githubusercontent.com/22608780/76535968-b658b300-64a1-11ea-91ae-fd6bed185e9a.png">

**Comment by ThomazFB** [comment]
## If we know for sure the new stats endpoint is available, then default to the new stats UI instead of displaying a banner message

As it is right now the `DashboardFragment` only shows the`MyStoreStatsAvailabillityCard` when the `isUsingV4Api` returns `true` and the `AppsPrefs` is configured to do so through the `shouldDisplayV4StatsAvailabilityBanner`. 

This behavior is triggered by the `onActivityCreated` event so it takes immediate effect. In that case, we want to abandon the `MyStoreStatsAvailabillityCard` visibility activation, delete the entire class from the project, and effectively do the same thing that the `onMyStoreStatsAvailabilityAccepted` method already do.

Also, we should remove the `MyStoreAvailabilityListener` implementation from the `DashboardFragment` since it won't be necessary anymore, and extract the V4 acceptance behavior to a private method so we can run this behavior in the scenario mentioned above. Looks like the V4 rejection scenario won't be needed anymore too, so this becomes a one-way door for the user, this way, if detect the V4 stats API availability, we just activate it, set it true in the AppPrefs and it becomes always available.

## Remove the beta feature option for using the improved stats since it will be enabled by default.

In order to remove the V4 Stats as a beta feature option, we should remove everything related to the `switchStatsV4UI` from the `BetaFeaturesFragment`. Looks like the Analytics field `SETTINGS_BETA_FEATURES_NEW_STATS_UI_TOGGLED` won't be necessary anymore too.

This will also require changes directly into the `MainSettingsFragment` deleting the `onV4StatsOptionChanged` from the `AppSettingsListener` and the counterpart implementation of it in the `AppSettingsActivity`.

## Update the date in the message shown in the image below to September 1, 2020.

* Just changing the date on the `my_store_stats_availability_message` string asset will probably solve it. But should check how to handle string translations for other regions for the project.

**Comment by AmandaRiu** [comment]
This looks like an excellent plan @ThomazFB

**Comment by anitaa1990** [comment]
This is a really great plan @ThomazFB! Sorry for the late response here but I wanted to add some points that might be worth noting when implementing.

> As it is right now the DashboardFragment only shows theMyStoreStatsAvailabillityCard when the isUsingV4Api returns true and the AppsPrefs is configured to do so through the shouldDisplayV4StatsAvailabilityBanner.

The reason we added a banner here, in the first place, was because the API call to fetch the stats v4 data took more around 900ms - 1.1s at times. So we just started out by displaying the old stats and a few seconds later came to know that the new stats is available. At this point, it wouldn't be good user experience to suddenly change to the new stats UI. So we added a banner to let the user know it's available, if they want to take a look at it 😅

I mention this because since we would be removing the old stats UI, we might want to display some sort of loading view before displaying the new stats here 😄 

Second point was that, there might be scenarios where the v4 stats for a site is available but the user might have disabled it on their site. In this case, the v4 stats will no longer be available and we would need to display this empty view in the stats screen.

<img width="300"  src="https://user-images.githubusercontent.com/22608780/76737494-e4ceda80-678e-11ea-879a-f95c228182c8.png">

There is an open issue here in #2068 to track that but this wasn't mentioned anywhere so I thought I'd let you know :D

**Comment by ThomazFB** [comment]
Hey @anitaa1990, thank you so much for your feedback!! Just to be sure, I have a few questions about those points you mentioned 😬 😬 😬 .

>I mention this because since we would be removing the old stats UI, we might want to display some sort of loading view before displaying the new stats here 😄

About the loading time to fetch the V4 stats, since we're making the V4 the default, in this case, wouldn't the user be placed directly into the V4 instead of going through the V3? I'm not sure about it, but it looks like the V4 stats already have a loading behavior as displayed on the screenshot below. Do you think this case would require a different kind of loading instead of the current one?

![Screenshot_1592965990](https://user-images.githubusercontent.com/5920403/85491920-ba20c900-b5aa-11ea-8b38-4a3252d29bee.png)

>there might be scenarios where the v4 stats for a site is available but the user might have disabled it on their site. In this case, the v4 stats will no longer be available and we would need to display this empty view in the stats screen.

Just to be sure, but this point you mentioned should be only implemented after we completely disable the Stats V3, right? If I implement it right now, wouldn't we completely block the V3 to be accessible for users? 🤔 

Thank you a lot for your time!

**Comment by anitaa1990** [comment]
Hey @ThomazFB, sorry for not replying to this before! 

> About the loading time to fetch the V4 stats, since we're making the V4 the default, in this case, wouldn't the user be placed directly into the V4 instead of going through the V3? I'm not sure about it, but it looks like the V4 stats already have a loading behavior as displayed on the screenshot below. Do you think this case would require a different kind of loading instead of the current one?

Yup, we do have a skeleton view loading behaviour for v4 as well 😄 I think we display the skeleton view only when there is no previous data available. Otherwise, we usually just display the existing stats data and then replace that once the new data comes in. We can use the existing ones no issues at all with that! I was just adding points to consider (or rather potential scenarios to test when we implement 😄) 

> Just to be sure, but this point you mentioned should be only implemented after we completely disable the Stats V3, right? If I implement it right now, wouldn't we completely block the V3 to be accessible for users? 🤔

Yup, this scenario would happen only after we disable v3 stats. This point wasn't mentioned in the issue description so wasn't sure if this was tracked. Consider a scenario where the new stats is enabled for a site in the app. We display that to the user and then make an API call to fetch new v4 data in the meantime. Now, if we find that the v4 stats is disabled. We should display the empty view I mentioned previously, in this case.

Hope that makes sense! Feel free to reach out in case of any doubts/issues/complaints 🤣

**Comment by ThomazFB** [comment]
Awesome! Thank you so much for explaining those points and for giving me so much context, I truly appreciate it @anitaa1990! 

> Yup, we do have a skeleton view loading behaviour for v4 as well 😄 I think we display the skeleton view only when there is no previous data available. Otherwise, we usually just display the existing stats data and then replace that once the new data comes in. We can use the existing ones no issues at all with that! I was just adding points to consider (or rather potential scenarios to test when we implement 😄)

 I'll try to do some tests with the new data refresh to get more context about the data refresh on the V4 view! 

> Yup, this scenario would happen only after we disable v3 stats. This point wasn't mentioned in the issue description so wasn't sure if this was tracked. Consider a scenario where the new stats is enabled for a site in the app. We display that to the user and then make an API call to fetch new v4 data in the meantime. Now, if we find that the v4 stats is disabled. We should display the empty view I mentioned previously, in this case.

Got it! So, from what I'm seeing here, it looks like we would like to completely turn down the `DashboardFragment`, and instead of creating it, we will display the empty view you described.

**Comment by AmandaRiu** [comment]
This is complete and in production. Closing ticket.
