### ISSUE TITLE
Notifications: Allow for only displaying a new order notification when order total is above $0.00

### ISSUE THREAD

**Issue by thsbrown** [woocommerce/woocommerce-android#2725]
**Is your feature request related to a problem? Please describe.**
Currently new order notifications come in regardless of the respective price of the order. I think this totally make sense, but if you have a lot of free content on your site (as we do) you can get inundated with new order notifications for the free content.

In theory this makes total sense as technically these are new orders, in reality though we don't really see these as "new orders".

**Describe the solution you'd like**
I would love it if there were a way to limit the new order notification to appear only when order totals are above $0.00. This way we would no longer be inundated with these new order notifications for orders that are only in relations to free content.

**Describe alternatives you've considered**
Perhaps the notification i'm after is not a new order notification but perhaps a "New Purchase Order" notification. Maybe there are just several types of notifications in relation to purchase totals that you can enable or disable.

**Comment by AmandaRiu** [comment]
Thank you for using the Woo Mobile app @thsbrown! This is a fantastic feature request but feature requests are not currently processed in GitHub (especially since we'd want to add this same functionality to both iOS and Android). Please go to [this link](http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=84283) to either up-vote this feature on the ideas board, or to add a new feature request if it doesn't already exist.
