### ISSUE TITLE
IllegalStateException: Fragment already added

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2776]
There are a bunch of fragment already added exceptions happening on the main fragments i.e. `OrderListFragment`, `NotifsFragment`, `ProductListFragment` and `AztecFragment`.

This issue just consolidates all the crashes happening with this particular exception since I think a common fix for all of the crashes here is required for a fix.

```
IllegalStateException: Fragment AztecEditorFragment{7c42614} (38cb57bb-f38e-448e-bdc9-17938bb782fd)} not attached to an activity.
    at com.woocommerce.android.ui.aztec.AztecEditorFragment.onRedoEnabled(AztecEditorFragment.kt:228)
...
(7 additional frame(s) were not displayed)

Fragment AztecEditorFragment{7c42614} (38cb57bb-f38e-448e-bdc9-17938bb782fd)} not attached to an activity.
```

```
IllegalStateException: Fragment already added: ProductListFragment{2be8fec} (05f27063-a596-45f0-a7d2-06d1080b3186) id=0x7f0a00dd ProductListFragment}
```

```
IllegalStateException: Fragment already added: NotifsListFragment{12bc979 #2 id=0x7f0a00a4 NotifsListFragment}
    at com.woocommerce.android.ui.main.MainActivity.onSaveInstanceState(MainActivity.kt:219)
```

```
IllegalStateException: Fragment already added: OrderListFragment{bf65647} (34b36c73-b282-40bb-8cbb-acb2e4afac02) id=0x7f0a00df OrderListFragment}
```

**Comment by anitaa1990** [comment]
I think this should be fixed in v5.9 since we have migrated all the top level fragments to use navigation controller in #3446. I'll mark this as closed for now and we can reopen it if needed.

**Comment by anitaa1990** [comment]
I spoke too soon, this is still happening in the Order list screen in v5.9-rc-1 so reopening 🤦‍♀️

**Comment by hichamboushaba** [comment]
@anitaa1990 as the issue is happening only in Order list screen, I thought that it's related to push notifications, and that was correct, I was able to reproduce it using the following steps:

Make sure you are using 5.9-rc1
1. Open orders screen.
2. Click on one of the orders, and then click on the orders tab before the bottom nav view is hidden.
3. Notice that the bottom navigation view is still visible, while the order detail is shown.
4. Place an order on the site.
5. Click on the push notification.
6. Notice that the order detail of the new order is shown.
7. Click on back button.
8. Notice the crash, with the same error as this report.

If this is the only way to reproduce this, then it should be fixed by the PR: #3485, so I'll close the ticket, and if it pops again later, we'll analyze it more.

**Comment by anitaa1990** [comment]
Great detective work @hichamboushaba! Thank you for taking a look at this one 😄

**Comment by anitaa1990** [comment]
Re-opening this issue since it seems to be happening in the latest release (5.9) to aleast 7 users. But it has only happened in the `OrderListFragment` so far.

**Comment by anitaa1990** [comment]
I'm closing this issue since we have refactored the top level fragments and the crash that is happening is not related to the crash mentioned in this issue.
