### ISSUE TITLE
Unified Login: Links and other highlight colors are blue (should be pink)

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#2890]
**Describe the bug**

According to the designs (and Woo color scheme) I expect links and other highlight colors to be pink. However, they are blue (WordPress blue) instead. This includes:

* The label and outline for fields that have focus
* Links such as the "Find your site address" help link (on the site address screen)
* "Need more help?" and "OK" buttons in the "What's my site address" modal

**To Reproduce**

1. Start logged out of the app.
2. Tap the "Enter your store address" button.
3. Notice the "Site address" field has focus and is outlined in blue, and the "Find your site address" link is blue.
4. Tap the "Find your site address" link.
5. Notice the modal that appears has buttons ("Need more help?" and "OK") in blue.

**Screenshots**

<img src="https://user-images.githubusercontent.com/8658164/93899996-d12ba000-fcec-11ea-9da6-8c05c79547fb.png" width="300px">
<img src="https://user-images.githubusercontent.com/8658164/93900000-d25ccd00-fcec-11ea-9e92-c676dade9a62.png" width="300px">
<img src="https://user-images.githubusercontent.com/8658164/93900006-d38dfa00-fcec-11ea-9720-354a0a7348f2.png" width="300px">

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 5.1-rc-1

cc @AmandaRiu

**Comment by AmandaRiu** [comment]
@Garance91540 I'm working on applying the appropriate styles here and have run into a snag. The text buttons and text outline components in android use the `colorPrimary` value by default which would be our _purple,_ but in the designs we're using _pink_ for these two items (`colorSecondary`). Since the login library is shared with the WordPress app it will be a much bigger change to break this out and will require changes on both platforms. Ideally both platforms would use the material design default of `colorPrimary`. Is it possible to switch over to this color? Here's a comparison for visual reference:

colorSecondary | colorPrimary
-- | --
![Screenshot_1600804238](https://user-images.githubusercontent.com/5810477/93930448-64fc6c80-fceb-11ea-94c6-c942ea55097e.png)|![Screenshot_1600803838](https://user-images.githubusercontent.com/5810477/93930453-66c63000-fceb-11ea-9f5b-896856729e28.png)
![Screenshot_1600803782](https://user-images.githubusercontent.com/5810477/93930482-70e82e80-fceb-11ea-96be-07343a88f12e.png)|![Screenshot_1600803205](https://user-images.githubusercontent.com/5810477/93930500-79d90000-fceb-11ea-94e3-2192008f4a2b.png)

**Comment by Garance91540** [comment]
Hi Amanda

All of our CTAs are currently using Pink 50 in the app, so I think we should stick with it if possible for CTAs. In that case, maybe this means we switch what we call "PrimaryColor" in the app to the Pink 50? (Is it what you were suggesting?)

https://d.pr/i/MP45N2

**Comment by AmandaRiu** [comment]
> Hi Amanda
> 
> All of our CTAs are currently using Pink 50 in the app, so I think we should stick with it if possible for CTAs. In that case, maybe this means we switch what we call "PrimaryColor" in the app to the Pink 50? (Is it what you were suggesting?)
> 
> https://d.pr/i/MP45N2

@Garance91540 No I'm referring to the text input outline and the text underneath. WordPress is using their primary color of blue - which is the standard for material design - but the designs show pink which deviates from both the standard and from the design of the shared login library. I'm asking if we can switch the design to using our primary color of purple for this part:

![Screen Shot 2020-09-23 at 9 39 05 AM](https://user-images.githubusercontent.com/5810477/94020184-a2f7a000-fd80-11ea-9fde-8762c9ee8f30.png)

**Comment by Garance91540** [comment]
Hi Amanda, gotcha,

"Find your site address" is a CTA link, so it should be pink to be consistent with the rest of the CTAs in the app. As per the field selector, we are currently using purple in the app, so if we stick with purple here that's all good! Now if the link color and the field selector have to be the same, in that case it should be pink 50.

**Comment by AmandaRiu** [comment]
Fixed in PR #2904. Closing.
