### ISSUE TITLE
Product images in order detail not displaying after downloading

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#3034]
The product images aren't showing up in the order detail if they haven't been downloaded yet. For example, the gif below starts after a fresh install so no product images have been downloaded. I clicked on an order and waited, and none of the images loaded. I go back to the order list and click back into the order -- images appear. 

<img src="https://user-images.githubusercontent.com/5810477/96190052-8f6acf80-0f0f-11eb-9ec0-440ffd7e5820.gif" width="320"/>

**Comment by nbradbury** [comment]
The problem is the order product list uses `ProductImageMapper` to get a product’s image. If it’s not already cached then `ProductImageMapper` will dispatch a request to fetch that product so we know the product image.

What needs to happen is to capture the `onProductChanged` event and then tell the order product list to load that product (since we now know the image).
