### ISSUE TITLE
Remove SKU from order detail

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3061]
We currently show the product SKU on order detail, but this has been removed from the latest design.

<img width="492" alt="Screen Shot 2020-10-21 at 3 58 52 PM" src="https://user-images.githubusercontent.com/3903757/96776020-67b7b380-13b6-11eb-9f3a-f1990871a002.png">

**Comment by anitaa1990** [comment]
Thanks for filing this issue @nbradbury! That screenshot seems to be from an older version of the app and a bit misleading since it only includes the product title 😅 

This seems to be right one? Taken from this p2 thread (`p91TBi-2CE`)
<img width="878" alt="screen-shot-2020-04-08-at-2 26 39-pm" src="https://user-images.githubusercontent.com/22608780/96808858-55ca2500-1437-11eb-9fbf-25231893b32f.png">
