### ISSUE TITLE
[Products M4 beta]: Disable the beta switch in Settings page by default

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3067]
It looks like when we update the app from a previous version which has the Beta switch enabled previously, the Beta switch is turned on by default. It makes sense to disable the Beta switch by default for M4.

### To test
- Install a previous version of the app, that includes the Beta switch for M3. Switch on the M3 beta setting.
- Install the latest beta version of the app and click on the Settings icon.
- Notice the Beta features Products m4 switch is enabled by default.

cc @woocommerce/android-developers

**Comment by shiki** [comment]
@anitaa1990 Since we're removing the M4 flag (https://github.com/woocommerce/woocommerce-android/pull/3161), is this task is still valid?

**Comment by anitaa1990** [comment]
I think the issue is that every time the app is updated with a new Products version, the beta switch should be turned off by default. Currently, that's not the case. This would be an issue even with future products releases so definitely still valid 👍

**Comment by AmandaRiu** [comment]
@anitaa1990 I was going to work on this, but I'm not sure I understand what is being asked. Currently there is no beta switch active in the app so this is probably just difficult to visualize at the moment, but thinking through the process it seems like maybe the next time there is one and another milestone is released then the developer removing that milestone from code would need to set the beta switch to false on the next install. I'm going to unassign this ticket from myself for now since I don't think there's anything I can do just yet.

**Comment by anitaa1990** [comment]
We're not using the beta switch anymore so closing this issue. We can open it again if we decide to use the Beta settings feature in the app again 👍
