### ISSUE TITLE
The Orders status bar appears in Products after recovering from the standby

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#3077]
After leaving for a night my Samsung S10 in standby, with the app opened in background, when I unlocked it the first screen showed was the Order tab (if I remember correct), but tapping on Products happened this:

<img src="https://user-images.githubusercontent.com/495617/97016012-83ed5900-154c-11eb-9164-86dc55f57648.jpg" width=300 />

As you can see, the navbar of Orders (the one which shows `Processing` and `All Orders`) is now showed also in the product list and in the product detail. Switching between the two options nothing happens. Returning to Orders, and re-selecting the Products tab solved the issue.

**Comment by pmusolino** [comment]
If I put the phone on standby I'm not able to reproduce it. Perhaps the operating system had frozen the app after quite some time? 🤷‍♂️

**Comment by anitaa1990** [comment]
Hey @pmusolino, this seems related to the [overlap issue](https://github.com/woocommerce/woocommerce-android/issues/3411) that was fixed in [this PR](https://github.com/woocommerce/woocommerce-android/pull/3446) sometime ago. Given that it hasn't happened again, I'm closing this issue but feel free to re-open it if you face the same issue again 😅
