### ISSUE TITLE
Drag-and-drop linked products

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3100]
Originally #3042 included re-ordering linked products, but this is a big enough task that we're moving it to a separate issue.

<img src="https://user-images.githubusercontent.com/3903757/97451316-03db4080-190a-11eb-89f6-b9d416bb28dd.png" width="300">

---

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/3171

**Comment by AliSoftware** [comment]
@nbradbury Moving this to 5.5 since 5.4 is ❄️-ing today

**Comment by wzieba** [comment]
@Garance91540 👋  currently we show icons for the products on this list and I think it's a cool thing to have:

<img width="350" alt="Screenshot 2021-03-17 at 13 59 03" src="https://user-images.githubusercontent.com/5845095/111471348-19ba9800-8729-11eb-9dea-76d31b5b8064.png">

WDYT about placing this "drag&drop holder" (those 3 lines) to the left like here:
<img width="350" alt="Screenshot 2021-03-17 at 14 02 02" src="https://user-images.githubusercontent.com/5845095/111471662-6b632280-8729-11eb-8e41-334a49b827cd.png">

and then remove would be done by swipe gesture? [Like here](https://kstatic.googleusercontent.com/files/1c876587a9a56a59f907898a0ce3915220f730d58fc238e123a756175db0894bab249c4a2159ee92f776df12168cf37e67529898caaf4e52c3013400eb33cfb7) Samples are from [Material Design docs](https://material.io/components/lists#behavior)

I'm only worried that users might are not used to swipe gestures in the app so it might be confusing for them to understand how to remove product from the list. What do you think?

**Comment by Garance91540** [comment]
Hi @wzieba , I think keeping the images thumbnails make sense indeed. I think we should introduce a proper edit mode to the app for list items, since we have several occurrences of this pattern in the app (ie Grouped products). Here's how it could work:

<img width="667" alt="Screen Shot 2021-03-18 at 4 27 55 PM" src="https://user-images.githubusercontent.com/28450084/111652086-1269bc00-8807-11eb-8e00-c074b4a4166f.png">

I also added iOS designs to the Products Figma file to make sure it's implemented in the same way on iOS cc @shiki 
<img width="544" alt="Screen Shot 2021-03-18 at 4 29 43 PM" src="https://user-images.githubusercontent.com/28450084/111652197-2d3c3080-8807-11eb-878e-f51f34847da0.png">

**Comment by wzieba** [comment]
Sure @Garance91540 looks great and is in-sync with other places like drag&drop for images of the product. Thank you for working on that!

**Comment by nbradbury** [comment]
Marking this "on hold" because we've turned it into a trial project.

**Comment by malinajirka** [comment]
@nbradbury Should we mark this as "Won't fix" and close it since the backend doesn't support retaining the order of linked products ([source](https://github.com/woocommerce/woocommerce-android/pull/3940#issuecomment-834329502))?

**Comment by nbradbury** [comment]
@malinajirka Good call, I'll close this.
