### ISSUE TITLE
[Products M1]: Display missing shipping information in Product detail

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3144]
It looks like the Shipping section doesn’t display the full shipping settings. For example, when we enter the weight but not the width or the height, the dimensions are not reflected in the Product detail screen. We should display the actual dimensions, even if some are missing. 

### To reproduce
- Click on a Product from the Products tab.
- Click on the Shipping section.
- Add ~weight~ width but do not add height or length.
- Click on the DONE menu button.
- Notice that the weight dimension is not displayed.

**Comment by ParaskP7** [comment]
I have spent a good amount of time today to look into this issue @anitaa1990, getting familiar with the codebase, the below related classes/files and last but not least, the function responsible for creating the to be displayed values, see below:
- `ProductDetailFragment.kt`
- `ProductDetailViewModel.kt`
- `ProductPropertyCardsAdapter.kt`
- `ProductPropertyCardViewHolder`
- `WCProductPropertyCardView`
- `ProductPropertiesAdapter`
- `PropertyGroupViewHolder`
- `PropertyGroupViewHolder.getPropertyValue(...)`

From my investigation and testing it seems that this is no longer an issue, I have tried to reproduce it, following the steps above, but what I got is the below:

<img src="https://user-images.githubusercontent.com/9729923/99677798-c9853f00-2a82-11eb-956a-240037a63c03.png" width="250" height="500">   <img src="https://user-images.githubusercontent.com/9729923/99677821-cf7b2000-2a82-11eb-8a79-13ea76977451.png" width="250" height="500">
<img src="https://user-images.githubusercontent.com/9729923/99677843-d5710100-2a82-11eb-8191-cc8295aa5a4f.png" width="250" height="500">   <img src="https://user-images.githubusercontent.com/9729923/99677910-e9b4fe00-2a82-11eb-955c-482c9e8ecb3b.png" width="250" height="500">

I am not sure if that was a problem before or if I am not doing it correctly, since it seems that this issue is pretty knew and the logic with the `WCProductPropertyCardView` and `PropertyGroupViewHolder` was last updated prior to chat. It might be that something got updated in between, which fixed that, not sure.

Please advise.

**Comment by anitaa1990** [comment]
Sorry @ParaskP7! I think I added the reproduction steps wrong here 🤦‍♀️ We need to add `width` or `height` or `length` and leave the remaining two items blank and then click on the `DONE` button.

**Comment by ParaskP7** [comment]
No worries @anitaa1990! Yes, I can confirm that indeed this is a problem and I just reproduced it myself. Will now work on solving the issue. Many thanks for your quick response! 🤗
