### ISSUE TITLE
Accessibility: "ADD" menu option in AddOrderNotesActivity

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#338]
### Expected behavior
The "ADD" menu option is announced as "add" by TalkBack

### Actual behavior
The "ADD" menu option is announced as "A.D.D" by TalkBack

<img width="307" alt="screen shot 2018-08-31 at 1 42 40 pm" src="https://user-images.githubusercontent.com/5810477/44927780-caa3e780-ad23-11e8-844e-9db98d75f46d.png">

**Comment by SiobhyB** [comment]
I tested this with version 4-0-rc-2 of the app and it seems this issue may have been resolved somewhere along the line. 

TalkBack announced "add" (rather than spelling out the individual letters "A.D.D.") in my testing.

@AmandaRiu, is it okay to close this issue or are you still able to replicate?

**Comment by AmandaRiu** [comment]
I'm good closing it. Thanks @SiobhyB !
