### ISSUE TITLE
Clicking on a variable product from the Order detail screen - redirects to the product detail page

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3390]
Clicking on a variable product from the Order detail screen redirects to the product detail page but should redirect to the variation page. This means none of the variation detail is actually displayed.

<img src="https://user-images.githubusercontent.com/22608780/103504403-517da780-4e7d-11eb-963b-029ca792d0a2.png" width="300"/>

**Comment by AliSoftware** [comment]
Code-freezing release/5.9 today.

As it seem this issue was planned for milestone 5.9 but hasn't been closed, it should either be closed if the bug has in fact been fixed in practice but forgot to be closed, or it will have to either be fixed directly on the release/5.9 branch very soon, or be moved to milestone 6.0.

**Comment by nbradbury** [comment]
Dup of #3812, addressed in #3822
