### ISSUE TITLE
Display Weekly Stats Mon thru Sun (instead of Sun thru Sat) 

### ISSUE THREAD

**Issue by ericamQA** [woocommerce/woocommerce-android#3472]
**Describe the bug**
When viewing stats in the Woo Android app, the week is shown as Sun through Saturday (unlike the browser or iOS app) 
Report here: 3677458-zen

**To Reproduce**
1. Go to WP-Admin
2. Click on Stats
3. Select the "Store" tab and the "Weeks" view
4. Notice that the week is displayed Monday through Sunday (this is not the case in the mobile Android app, it's Sunday through Saturday instead, dividing the weekend.)

**Screenshots**
![image](https://user-images.githubusercontent.com/44411833/105656890-4375e200-5e91-11eb-8b8d-38a38d0c6c76.png)

**Expected behavior**
The Android version of the app would display the weekly stats in the same way that the browser and iOS versions do (Monday through Sunday) 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: multiple
- Android version: 11
- WooCommerce Android version: 5.7

</details>

**Comment by malinajirka** [comment]
Thanks for the report!

I'd like to confirm the desired behavior with you all. The first day of week depends on a region. Some regions/countries use Saturday some use Sunday and some use Monday. 

The Android app currently uses "Locale.ROOT" which has "firstDayOfWeek" set to Sunday. The app completely ignores User's locale and always shows Sunday as the first day of week.

The question is if we want to hardcode "Monday" as the first day of week for all users or if we want to start taking User's locale into account. 

IMO no matter what we hardcode some users will be always confused. Especially, since the graph displays just dates (not day names). I'd personally start using user's locale and fix iOS/web if necessary. Wdyt @wpericam @shiki @anitaa1990 ?

**Comment by nbradbury** [comment]
> The question is if we want to hardcode "Monday" as the first day of week for all users or if we want to start taking User's locale into account.

FWIW, I'd opt to rely on the user's locale.

**Comment by shiki** [comment]
It looks like the first day of the week that the WCAdmin stats uses is based on the WordPress **Week Starts On** setting. I changed this to Tuesday and the Last Week range on the stats changed accordingly to use Tuesday as the beginning of the range. 

<img src="https://user-images.githubusercontent.com/198826/111227731-9ffba080-85a8-11eb-9186-c3af91a3ffa6.png" width="500">

If possible, we should probably use that setting instead so that it's a more consistent experience. If that's not straightforward to do at the moment, then it makes sense to use the locale as the default instead of hardcoding.

**Comment by shiki** [comment]
Looks like the [`start_of_week` setting](https://developer.wordpress.org/rest-api/reference/settings/) is available from the WordPress REST API. Not sure if we already have access to that. 🤔
