### ISSUE TITLE
Product filter not applied after search

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#3554]
If you apply a filter to the product list and then do a product search, the filter isn't applied to the search results. 

In this screenshot I chose a "Grouped products" filter, which would match a single product, but when I searched the results were from all products.

![Screenshot_20210211_071403](https://user-images.githubusercontent.com/3903757/107635362-018ebf00-6c39-11eb-803c-d2da32153369.png)

**Comment by malinajirka** [comment]
I think this conflicts with the behavior described here https://github.com/woocommerce/woocommerce-android/issues/3259. It seems the desired behavior is to hide the "Sort and filters" bar. Can you confirm @Garance91540, thanks!

**Comment by Garance91540** [comment]
Hi!

> If you apply a filter to the product list and then do a product search, the filter isn't applied to the search results.

Thanks for flagging this, it's not the correct behavior indeed. When a filter is applied and user tries to search a product, we should search amongst the filtered products, and not all products. 

In  #3259, I flagged that we should remove the "Filter" and "Sort" buttons from the search screen because they visually clutter it. But the filter selection is still applied. 

 iOS for reference:

<img width="401" alt="Screen Shot 2021-10-01 at 9 30 56 AM" src="https://user-images.githubusercontent.com/28450084/135655874-168732f7-cd6f-47aa-869c-6e4664e2fbe7.png">

**Comment by malinajirka** [comment]
Thanks for the reply @Garance91540! I'm a bit worried it might not be intuitive that the filter is applied even when it's not visible and users aren't able to cancel it unless they leave the screen. But if it's the intended behavior, I'd at least consider changing "Search all products" hint to "Search filtered products" or something in that sense, wdyt?

**Comment by Garance91540** [comment]
> changing "Search all products" hint to "Search filtered products" or something in that sense, wdyt?

Sounds good @malinajirka !
