### ISSUE TITLE
FluxC: Add persistence & networking for the Customer

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#3605]
Add the following components:

- [ ] A REST client for customer creation & fetching
- [ ] SQL utilities for storing and retrieving the Customer entities
- [ ] A Store for local loading, fetching and creating customers by the client (Woo app)
- [ ] Testing UI in the `example` app module
- Unit tests

**Comment by kidinov** [comment]
Subtasks [based on](https://appsp2.wordpress.com/2021/02/25/andreys-trial-progress-changes-in-fluxc/):

1. REST client for a customer fetching. SQL Utils for storing and retrieving. And a store itself
2. Unit tests for 1 (not the best approach to do unit testing as a separate step but otherwise the change can be too big)
3. REST client for customers fetching. SQL Utils for storing and retrieving. And a store itself
4. Unit tests for 2
5. REST client for a customer creation. SQL Utils for storing and retrieving. And a store itself
6. Unit tests for 3
7. Testing UI for all 3 features, because we can create/fetch customer/customers already

**Comment by kidinov** [comment]
Following the feedback, I got
```
7. Testing UI for all 3 features, because we can create/fetch customer/customers already
```

Is divided on:

```
7. Testing UI for fetching a customer
8. Testing UI for fetch customers
9. Testing UI for creating a customer
```
