### ISSUE TITLE
Unwanted fetching all subscriptions of user when fetching user's websites

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#3911]
When user logs in for the first time, when choosing site, we fetch all user subscriptions: `public-api.wordpress.com/rest/v1.2/read/following/mine/`

It was added in https://github.com/woocommerce/woocommerce-android/commit/09a0852581dd9a3a6b15109f3a8e9a80e644fbbb#diff-07d3f014c102c47ee01a0452759b18ae392c2bdc7a66fb182d105e0bce575467R304 commit. 
We should investigate if it's needed in Woo use case and if not - remove it.

According to Sentry Performance Monitoring, this call takes around 5 seconds: p91TBi-4y5-p2#comment-4275

**Comment by JorgeMucientes** [comment]
**Extra Context** 
`public-api.wordpress.com/rest/v1.2/read/following/mine/` request is only fired when log in with WP.com email/password and having 2FA enabled. When 2FA is not enabled the request is not fired. So, it's clear from this we don't need this in WooCommerce app login to be fired, and makes me wonder if it's needed in WordPress app either. 

Additionally, it's worth highlighting that the request (while unnecessary) it takes around 1s on average for a testing account with a couple of sites. The reason it seemed to take around ~5s in the measures, it's because it was being measured for a Automattic WP.com email account, which is subscribed to tons of P2 sites.
