### ISSUE TITLE
Update Gradle plugin so new version of detekt can be used

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#4043]

**Comment by wzieba** [comment]
Do you mean `Kotlin Gradle plugin` or `Android Gradle plugin`?

If `AGP` then we should assert that the same version is used in other projects in order to keep included builds working. Platform 9 team plans to update `AGP` to `4.2.0` soon.

But anyway, we use `AGP` in version `4.0.1` and `KGP` in version `1.4.32` - is there a need to update anything in order to use Detekt?

**Comment by kidinov** [comment]
@wzieba Sorry, I was talking about AGP. I briefly tried to install detekt and it didn't work due to (apparently) the old AGP we use. More research is needed anyway.

> If AGP then we should assert that the same version is used in other projects in order to keep included builds working. Platform 9 team plans to update AGP to 4.2.0 soon.

I see that we include FluxC?

**Comment by wzieba** [comment]
> Sorry, I was talking about AGP. I briefly tried to install detekt and it didn't work due to (apparently) the old AGP we use. 

Sure, thanks for clarification! Maybe the error you've encountered signaled something else before in stacktrace because even Detekt's Gradle Plugin documentation [shows examples with AGP `4.0.1`.](https://detekt.github.io/detekt/gradle.html)

> I see that we include FluxC?

Typically we have it from Jitpacks artifactory but it's possible to use it as included build. It's super useful if you change something in FluxC and want to build Woo app from this code, without any additional overhead. See [`local-builds.gradle-example`](https://github.com/woocommerce/woocommerce-android/blob/develop/local-builds.gradle-example) for more details.

If you'll need any help regarding Gradle plugins, please feel free to ping me - I'll be eager to help! 🙌

**Comment by wzieba** [comment]
I think we can close this issue: we use AGP in version `7.1.1` and pretty new Detekt `1.19.0`.
