### ISSUE TITLE
Notifications code clean up

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#4364]
As @anitaa1990 pointed out in P2 post ( p91TBi-5nM-p2 ), we should clean up code related to notifications. Currently, this code is not tested and it's very difficult to add any tests. Also, we have a lot of code in `MainActivity` and it'd be nice to move it somewhere else.

A good start can be [`NotificationHandler`](https://github.com/woocommerce/woocommerce-android/blob/adeb3778f891e5ded28a7ad52be5c1af77129920/WooCommerce/src/main/kotlin/com/woocommerce/android/push/NotificationHandler.kt#L61).

**Comment by anitaa1990** [comment]
@wzieba, is this something you are planning to work on? Because as part of the notification support for multiple stores, this is something I was tackling in [here](https://github.com/woocommerce/woocommerce-android/compare/develop...woo/notifications-multiple-stores), since it's very much inter connected. 

But if you plan to work on it next sprint, I would appreciate a heads up since that would mean I need to refactor the code I'm working on and merge that with this one separately 😊

**Comment by wzieba** [comment]
> is this something you are planning to work on?

That was one of the things I was thinking of but you've got a good point - this is strictly connected with notification support for multiple stores. I'll totally pass on this to not cause any unnecessary merge conflicts, thanks for the awareness!

**Comment by anitaa1990** [comment]
Fixed in #4655
