### ISSUE TITLE
Chart empty view string not translated

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#4964]
While testing #4958 I noticed that an empty stats chart shows "No chart data available" in English despite the device being set to Hebrew.

![chart](https://user-images.githubusercontent.com/3903757/136376750-6ed84683-d215-4dcc-9f14-fcc27d1b8365.png)

**Comment by anitaa1990** [comment]
This text is coming from the Chart library and is displayed by default when we send 0 or null values. I believe we can override it at some point and use our own text here, which can then be made translatable

**Comment by backwardstruck** [comment]
@nbradbury I'm not sure that the issue is still happening:

<img src="https://github.com/woocommerce/woocommerce-android/assets/947561/1ae8494d-d1c6-490c-8550-8b88beed1d92" alt="Screenshot_20240214_164010" height="420">

but I did find a similar issue on a related screen:

<img src="https://github.com/woocommerce/woocommerce-android/assets/947561/a67b7ac0-c06a-4e41-b557-543d31fd7348" alt="Screenshot_20240214_163911" height="420" >

I can address that and/or the original issue if you are still able to reproduce.
