### ISSUE TITLE
Add Detekt `autocorrect` task

### ISSUE THREAD

**Issue by wzieba** [woocommerce/woocommerce-android#5173]
**Describe the bug**
In `detekt.yml` file we have `formatting.autocorrect=true` set but it seems it doesn't work - executing `detektAll` task doesn't fix fixable issues.

Only when I add the option in task configuration like
```
tasks.register("detektAll", Detekt) {
(...)
    autoCorrect = true
(...)
```

auto correct feature works (after running `detektAll`, some of the issues are fixed).

### Update

This issue is about adding a new task, similar to `detektAll` but with `autocorrect` enabled.

**Comment by hichamboushaba** [comment]
@wzieba, we added the option `formatting.autocorrect=true` to allow autocorrect to work with the detekt's [plugin](https://plugins.jetbrains.com/plugin/10761-detekt), if you install the plugin, you can invoke autocorrect from the context menu.
Personally, I would be against having `detektAll` re-formatting the code by itself, some people prefer to use the IDE's formatting tool, and they should be able to continue to do so, but that's just an opinion 🙂.

**Comment by wzieba** [comment]
Thanks for comment, I didn't know that `formatting.autocorrect=true` is supported by Detekt's IDE plugin and not by Gradle task - is that by design?

> Personally, I would be against having detektAll re-formatting the code by itself, some people prefer to use the IDE's formatting tool

WDYT about adding re-formatting to `detektAll` task and leaving `formatting.autocorrect=true` unchanged? This way we'll have working autoformat in both ways (IDE and Gradle) so everyone can choose preferred way.

**Comment by hichamboushaba** [comment]
> Thanks for comment, I didn't know that formatting.autocorrect=true is supported by Detekt's IDE plugin and not by Gradle task - is that by design?

That's not what I meant, I meant that we added it to make the AutoCorrect work with the plugin here https://github.com/woocommerce/woocommerce-android/pull/4353, but I don't know about the specifics of the configuration to say that it's not linked to the gradle task, maybe the gradle task needs both, the option, and specifying it explicitly in the task.

> WDYT about adding re-formatting to detektAll task and leaving formatting.autocorrect=true unchanged?

Personally, and here I speak only for myself 🙂, I don't want the task `detektAll` to reformat my code, for me `detektAll` is just a way to see what are the current issues with my code.
Another point, changing it might break the CI, since the CI calls it, then if it corrects the code itself, then it might not report the issues, and as it won't commit those changes, it will be misleading.

If we need a way to re-format the code using Gradle, then we can maybe create another Gradle task that uses invokes `detekt`s autocorrect, WDYT?

**Comment by wzieba** [comment]
Gotcha, but I'm not sure if I understand the cons here. 

> for me detektAll is just a way to see what are the current issues with my code

With `autocorrect = true` in Gradle task you will still see all issues reported. It firstly reports issues and then makes an attempt to handle fixable issues. 

>  changing it might break the CI

It shouldn't break CI as task will fail even if Detekt fixes the issues.

> If we need a way to re-format the code using Gradle, then we can maybe create another Gradle task that uses invokes detekts autocorrect, WDYT?

Sure, that's not a problem for me, I can just add a new task. I prefer it that way as it fixes issues in all of the edited files so I don't have to travel through files. I can't see it possible with IDE plugin.

**Comment by hichamboushaba** [comment]
> With autocorrect = true in Gradle task you will still see all issues reported. It firstly reports issues and then makes an attempt to handle fixable issues.

I never tested it, so I thought that it will not report the issues that it can fix by itself 🙂.

Using a different task for it is just an opinion, so feel free to discuss with the rest of the team if you prefer to add it to `detektAll` instead 🙂

**Comment by wzieba** [comment]
While I was working on this, I realized that the Detekt Gradle task accepts CLI arguments! So running 
```
./gradlew detektAll --auto-correct
``` 
resolves my issue without a need to add an additional task 🎉 . It's a pity to me I realized this so late.
