### ISSUE TITLE
[Mobile Payments][SDK 2] Update documentation.

### ISSUE THREAD

**Issue by ctarda** [woocommerce/woocommerce-android#5240]
The documentation for IPP has been referencing the BBPOS Chipper as the only supported reader. Now that we have merged support for the M2, we might need to update some of the documentation, including, but not limited to:

* The README files reference the Chipper as the only supported card reader
* The documentation in woo university might need to be updated
* Run a check of the FAQs and other internal documentation to update where needed

**Comment by kidinov** [comment]
Progress: 

- [x] FAQ PbTz5e-1fk-p2 
- [x] Troubleshooting PbTz5e-1ff-p2 (I considered adding missing address during location fetching, but I think it will be excessive because we handle this pretty much as happy flow and I don't think that logs will help anyhow)
- [ ] Supporting the reader PbTz5e-1fn-p2
- [x] Check Readme

**Comment by kidinov** [comment]
Reverting back due to pdfdoF-gA-p2

Reverted:

- [x] FAQ PbTz5e-1fk-p2 
- [x] Troubleshooting PbTz5e-1ff-p2 (I considered adding missing address during location fetching, but I think it will be excessive because we handle this pretty much as happy flow and I don't think that logs will help anyhow)
- [x] Supporting the reader PbTz5e-1fn-p2
- [x] Check Readme
