### ISSUE TITLE
Simple Payments: Order Details May Not Show Up After Device Rotation 

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5343]
## Describe the Bug

When the Take payment screen is shown and the device is rotated, pressing Done will not show the Order Details screen right away. It looks like I will have to navigate to a different tab and back to the Orders tab so that the Order Details screen will be presented.

## To Reproduce

1. Tap on + button.
2. When the Take payment screen is shown, rotate to landscape.
3. Enter and amount and press Done. 
4. Nothing happens and the Order Details screen is not shown. 
5. Tap on the Products tab.
6. Tap back on the Orders tab. The Order Details screen will be shown.

## Screenshots

https://user-images.githubusercontent.com/198826/143309626-4aee6f9f-a176-46e0-af15-2a3fd26a925f.mov

## Expected Behavior

The Order Details screen should be shown right away.

## Mobile Environment

- Device: Pixel 3

---

@nbradbury I think it's fine if this is fixed after the release.

**Comment by nbradbury** [comment]
Looks like this is a bigger issue that just simple payments. The problem is that `handleResult` isn't triggered [here](https://github.com/woocommerce/woocommerce-android/blob/5e83e5265cf09ef6466a424407bb6a2f36ba6555/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/list/OrderListFragment.kt#L310) if you rotate the device. But if you rotate the device again, it **is** triggered.
