### ISSUE TITLE
Rename "Onboarding" term in CardReaderOnboardingChecker class

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#5403]
Rename the "Onboarding" term in CardReaderOnboardingChecker class since we are no longer using it just for our onboarding use case. 

Refer to this comment https://github.com/woocommerce/woocommerce-android/pull/5375#discussion_r760983610

**Comment by malinajirka** [comment]
Before we move ahead with this task, I think it might be worth discussing it on slack. I feel like it's confusing but at the same time I realized we might be behind the point of an easy return. We'd probably want to update even all the strings - which are already translated and the translation would be removed. Some of our p2 posts are referring to it as onboarding flow, so that'd be confusing as well. Either way, I'm not saying we shouldn't do it, but I think it's worth discussing.

**Comment by AnirudhBhat** [comment]
Sure thing! That's the reason I didn't start working on this and created a separate issue for it to track. Thanks for all the input!

**Comment by malinajirka** [comment]
@AnirudhBhat I have been thinking about this for a while now and I'd personally vote for keeping the names as they are. We might want to perhaps add a comment on top of the class and mention some example usages? Wdyt?

**Comment by AnirudhBhat** [comment]
@malinajirka Sounds good to me. This would be a good start. We can revisit this later if we still have issues/confusion with the naming a few months down the road.
