### ISSUE TITLE
[Simple Payments] "Payment successful" Snackbar is shown after failed transaction

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#5848]
## Steps

1. Create a simple payment. 
2. Use 2.65 as the amount.
3. Do not charge the tax. 
4. Tap “Take payment”
5. Choose Card. 
6. Use the Stripe test card.
7. The transaction should fail with this error (or I think a random error):
 
    <img src="https://user-images.githubusercontent.com/198826/153658024-fbcc2b10-10d0-40fc-9875-597140af7be2.png" width="300">
8. Press Back (Android back button)
9. A “Payment successful” Snackbar is shown. Even though the transaction failed. 🤔 
    <img src="https://user-images.githubusercontent.com/198826/153658117-a18b4829-5382-4f7a-b7d3-d6d3d5503232.png" width="300">

**Comment by nbradbury** [comment]
Oof, just looked into this and it looks like `onCardReaderPaymentCompleted()` fires on both successful and failed payment.

**Comment by nbradbury** [comment]
Looks like this isn't specific to simple payments. Order detail also treats failed payment as a success and reloads the order list. 

@malinajirka Is this intentional? Both simple payment and order detail don't distinguish between a successful or failed card payment. Both of them call their respective view model's `onCardReaderPaymentCompleted` function.


```
handleDialogNotice<String>(
            key = CardReaderPaymentDialogFragment.KEY_CARD_PAYMENT_RESULT,
            entryId = R.id.orderDetailFragment
        ) {
            if (FeatureFlag.CARD_READER.isEnabled()) {
                viewModel.onCardReaderPaymentCompleted()
            }
        }
```

To reproduce this, tap an order in the order list that hasn't been paid yet, then step through the card payment flow. When you get to the "Tap or insert to pay" screen, back out and notice `viewModel.onCardReaderPaymentCompleted()` gets called.  Should there be some way to detect whether the payment failed here? Or am I simply misunderstanding how this should work?

**Comment by malinajirka** [comment]
I think the naming might be a bit misleading - 'onCardReaderPaymentCompleted` gets invoked no matter if the payment completed successfully or not. We want to reload the order detail even if the payment failed - it shouldn't be needed, but in a very rare scenarios the payment might fail because it was paid already -> we want to reload the order detail so the "collect payment" button disappears and the status of the order changes to "paid/complete".

**Comment by nbradbury** [comment]
@malinajirka Is there a way to detect whether the payment was successful?

**Comment by malinajirka** [comment]
I think we have a couple of options
1. Load the order from the database and check if it was paid (easy approach)
2. Return the result from the CardReaderPaymentFragment/ViewModel - we are currently returning only "notice" without any result state (this will require more changes, but shouldn't be too complicated)

Having said that, I'd consider reevaluating whether `TakePaymentViewModel` actually needs to know it - it's imho not its responsibility. The payment flow itself shows success/failure dialogs so the user knows the result of the payment. The `CardReaderPaymentViewModel` tracks success/failure of the payment so tracking is also unnecessary. Wdyt?

**Comment by nbradbury** [comment]
Good point about the snackbar being unnecessary, but we also want to track when a simple payment succeeds or fails. I think the second option sounds good.
