### ISSUE TITLE
[Feature Request] Support Additional File Types in Media Picker for Uploading Downloadable Files

### ISSUE THREAD

**Issue by igotdes** [woocommerce/woocommerce-android#6017]
The media picker library used for uploading downloadable files supports images, videos, and audio. However, it is currently only set up to accept images.

Related discussions:

- p91TBi-4UT-p2
- p91TBi-2XV-p2
- p1646901239210379-slack-C6H8C3G23

**Comment by rossanafmenezes** [comment]
I had planned to work on this issue during HACK Week, but due to other things it didn't happen as I planned. So I'm adding here some info I was able to find for future reference:

We currently use the WordPress media picker in the Woo App. The MediaType enum class contains the following: IMAGE, VIDEO, AUDIO, DOCUMENT

However, the enum class MediaTypes has a variable allowedTypes which only allows video and images. This is from the WordPress library and cannot be modified from the Woo codebase. 

I was also able to enable videos to been "seen"  in the Woo app [here](https://github.com/woocommerce/woocommerce-android/blob/a8c09fd44e18af5f43fa32daf9c650308243f10d/WooCommerce/src/main/kotlin/com/woocommerce/android/mediapicker/MediaPickerSetupFactory.kt#L15). So if you have a video on your site's media library, or on your phone you could actually see it from the Woo app. I haven't PRed it because it would make no difference due to the error mentioned below:

![Screen Shot 2022-06-17 at 12 27 51](https://user-images.githubusercontent.com/30724184/174623280-20812003-26ac-4454-86e2-d1ae02518971.png)

but trying to upload the file fails with the following errors. 


![Screen Shot 2022-06-17 at 12 28 15 PM](https://user-images.githubusercontent.com/30724184/174623384-90e907d3-a177-42b7-9755-cb6e60ac9900.png)


`2022-06-17 12:28:12.599 6995-7167/com.woocommerce.android.dev E/WordPress-UTILS: Error reading orientation of the file: /data/user/0/com.woocommerce.android.dev/cache/wp-1655483292533.mp4` 

`2022-06-17 12:40:02.238 8549-8698/com.woocommerce.android.dev E/WordPress-UTILS: Can't decode the resized picture.`

`2022-06-17 12:40:02.239 8549-8698/com.woocommerce.android.dev E/WordPress-MEDIA: Failed to create optimized image. Use the original picture instead.`

I did not have the time to investigate it further. I might come back to this issue but feel free to tackle it.

Things we should consider: Adding the option to upload video would be the easiest thing to do once the reason why the upload fails is addressed. However, we should consider making the changes to include documents.
