### ISSUE TITLE
Add onboarding check for Simple Payment

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#6127]
I also noticed the "Card" row in Simple Payments flow is not visible unless the user finished onboarding -> My understanding is that this PR introduces onboarding checks into the Simple Payment flow -> would it make sense to update the logic so the "Card" row is visible even before the onboarding is completed (we could use the existing CardReaderPaymentCollectibilityChecker)? Note: It's fine to do this in a separate PR or perhaps even preferred

context - https://github.com/woocommerce/woocommerce-android/pull/6021

**Comment by nbradbury** [comment]
@Ecarrion Related to this, I just tried creating a simple payment with a fresh install of the iOS app and it appears the "Card" option in simple payments appears regardless of the onboarding status. However, it takes a second or two to show up. What exactly is happening during that brief delay?

**Comment by Ecarrion** [comment]
HI @nbradbury, 

The "card" option is only shown if the merchant has completed the iPP - onboarding.

https://github.com/woocommerce/woocommerce-ios/blob/9edbb95d5065623df89f038ff04c88a69394037a/WooCommerce/Classes/ViewRelated/Orders/Simple%20Payments/Method/SimplePaymentsMethodsViewModel.swift#L220-L227

The delay you are experiencing is the app fetching data from the site to properly know if the onboarding has been completed or not. (Because you did it in a new ios-install without any data cached/stored.)

https://github.com/woocommerce/woocommerce-ios/blob/9edbb95d5065623df89f038ff04c88a69394037a/WooCommerce/Classes/ViewRelated/Dashboard/Settings/In-Person%20Payments/CardPresentPaymentsOnboardingUseCase.swift#L55-L62
