### ISSUE TITLE
Products: Empty filter result is unrecoverable

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#6349]
Filtering the product list using criteria that will result in an empty list will result in an empty screen. However, the filter buttons disappear and I could not change the filter anymore. 

## Steps

1. Navigate to Products
2. Choose a filter that will result in an empty result. I chose "Out of stock" because none of my products are out of stock.

https://user-images.githubusercontent.com/198826/164864793-c3aea1ad-c943-419c-8140-bade2c17120f.mp4

**Comment by shiki** [comment]
☝️ @hafizrahman or maybe @JorgeMucientes I think this is a bug that we might want to fix as soon as possible. But I leave it up to you to decide. Also please tag someone else if I tagged the wrong people. 😁

**Comment by hichamboushaba** [comment]
I think this is a regression because of this [PR](https://github.com/woocommerce/woocommerce-android/pull/6259), we didn't notice catch this issue there 🤦.
I don't think fixing this will be straightforward (sometimes I hate how nested scrolling works in Android), I suggest we revert the PR to fix the bug in the current release, and then invest some time in finding a proper solution, WDYT?

**Comment by shiki** [comment]
@hichamboushaba Looking at the problem described in https://github.com/woocommerce/woocommerce-android/issues/3260, I agree with you that we can revert the PR for now. 🙂
