### ISSUE TITLE
Track that the new "Payment Gateway selection" is shown

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#6630]
When the onboarding flow results in displaying "Select Payment Gateway" screen, we'll want to track the existing `CARD_PRESENT_ONBOARDING_NOT_COMPLETED` event with a new value of the `reason` attribute - perhaps something like "preferred_payment_gateway_not_selected".

Add new case for the new "Select Payment Gateway" screen [here](https://github.com/woocommerce/woocommerce-android/blob/1833f7994d21851e26c6dc6164000f8fa1033e59/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/cardreader/CardReaderTracker.kt#L121). 

Sync with iOS folks.

**Comment by toupper** [comment]
@rossanafmenezes @AnirudhBhat On iOS I used the string `card_present_select_payment_gateway_show`. Please use it or let me know if you think of a better name so we can synchronize :)
I didn't add  the reason properties because we can ascertain whether it came from settings or onboarding by checking the settings row tap event to be implemented in https://github.com/woocommerce/woocommerce-android/issues/6632
