### ISSUE TITLE
Page not refreshing after site switching

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#771]
**Describe the bug**
@bummytime was testing the feature on his S6 and found that the page he initiated the site switch from was not refreshing automatically after the site switch.

**Comment by bummytime** [comment]
Just because I love GIFs — here is the issue as I am seeing it:

#### Dashboard Screen
![dashboard_switcheroo](https://user-images.githubusercontent.com/154014/52588744-c9163980-2e02-11e9-950f-2a005be150d9.gif)

#### Order Screen
![orders_switcheroo](https://user-images.githubusercontent.com/154014/52588724-c0256800-2e02-11e9-9207-59e23381d05b.gif)

**Comment by nbradbury** [comment]
At first I wasn't able to reproduce this, but then I remembered I have the "Don't keep activities" dev option enabled (and I bet @AmandaRiu does, too). Disable that and this bug is easily reproducible.
