### ISSUE TITLE
java.lang.IllegalStateException: Marker added to finished log

### ISSUE THREAD

**Issue by jkmassel** [woocommerce/woocommerce-android#817]
From the logs, this looks like a case where the user has a very bad network connection (they were experiencing timeouts right before the crash).

I suspect this is Volley's bug, and not ours, but we may need more data – right now only a single user is experiencing it.

From Fabric:

Fatal Exception: java.lang.IllegalStateException: Marker added to finished log
       at com.android.volley.VolleyLog$MarkerLog.add(VolleyLog.java:132)
       at com.android.volley.Request.addMarker(Request.java:219)
       at com.android.volley.ExecutorDelivery.postError(ExecutorDelivery.java:66)
       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:165)
       at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

**Source:** 5c66f956f8b88c2963f5a1fe-fabric

**Comment by nbradbury** [comment]
[Here's](https://android.googlesource.com/platform/frameworks/volley/+/android-5.1.1_r13/src/com/android/volley/VolleyLog.java#127) the line in the Volley source code where this exception is thrown. It looks like the log has already been finished yet a call to add a log entry still occurs.

One possible fix mentioned [here](https://stackoverflow.com/a/28110821/1673548) is to use `VolleyLog.DEBUG = false` to disable debug logging, but I'm not sure we want to do that (or if it's even enabled in the first place).

**Comment by AmandaRiu** [comment]
This is a crash that is happening when Volley attempts to write to a finished log. We are seeing this crash only for a single user, and so far just 5 times. Some SO comments are recommending just setting `VolleyLog.DEBUG = false`, which I'm fine doing, but I don't _believe_ debug logging is enabled by default. Looking at Volley's `VolleyLog` code, they use `Log.isLoggable("Volley", VERBOSE)` to see if they should be logging. That method should return false since the default logging level for any tag is INFO unless a property is explicitly set. I've run `adb shell getprop | grep log.tag` and nothing is forcing it to be set on my test devices. However, device manufacturers are known to set their own properties so I'm guessing this is either something the user is manually forcing by running `adb shell setprop tag.log.Volley VERBOSE`, or the device manufacturer has it set.
