### ISSUE TITLE
Can't go back to My Store after viewing a pending order

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#818]
**Describe the bug**

When I start on the My Store dashboard with a pending order, I can view that order (in the "You can 1 order to fulfill" section). However, I can't get back to the My Store dashboard from the order details screen.

**To Reproduce**

1. Start with a pending order for your store.
2. Go to the "My store" dashboard.
3. Scroll down to the "You have 1 order to fulfill" section.
4. Tap on "View Order."
5. Note that there's no bottom tab navigation. Tap the device's back button to go back.
6. Result: The app closes instead of going back to the My store dashboard.

**Screenshots**

Here's a screencast of the steps I took: https://cloudup.com/cTRlhXe0S23

Order details screen:

![screenshot_20190220-110054](https://user-images.githubusercontent.com/8658164/53087459-22672280-34ff-11e9-9bef-d5250a71965b.png)

**Expected behavior**

I expected the back button to take me back to the My store dashboard. I also expected to see the bottom tab navigation, although I wouldn't have noticed it missing if the back button had worked as expected.

**Mobile Environment**
Please include:
- Device: moto e5 play
- Android version: 8.1.0
- WooCommerce Android version: 1.2-rc-2

**Comment by nbradbury** [comment]
It looks like what's happening is the bottom nav disappears when scrolling and doesn't reappear when moving to the orders tab. Since there's only one order there's no way to scroll the order list and make the bottom nav reappear. Fix should be to ensure the bottom nav is visible when switching tabs.

I'm not sure the back button should return to the dashboard, though. The material guidelines _used_ to say that the back button doesn't navigate between tabs, but that recommendation has since been removed.

**Comment by rachelmcr** [comment]
>I'm not sure the back button should return to the dashboard, though. The material guidelines _used_ to say that the back button doesn't navigate between tabs, but that recommendation has since been removed.

That makes sense. I think because the bottom nav didn't reappear this felt less like moving between tabs and more like moving to a screen from which I should be able to go back.
