### ISSUE TITLE
[Free Trial] [Test Plan Request] Handle external Site plan upgrade scenarios

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8585]
Summary
==========
If I upgrade through a browser and then tap on Upgrade Now in the app, I would expect for the screen to refresh to remove the banner (or show some sort of indication that it was actually already upgraded). Instead, I'm brought to a screen about different WordPress plan options.

<img src="https://user-images.githubusercontent.com/5920403/226222037-af0555f0-9b59-4320-9e4e-3ffd5360434a.png" width="300">

**Comment by wzieba** [comment]
Maybe we should move it to iteration 4, it sounds like a corner case (and it will disappear if user re-launched the app)

**Comment by shiki** [comment]
I hesitated on this. I feel like we should fix it as soon as possible, at least as part of the second iteration.  

When experienced by the merchant, it impacts their trust in the app and Woo in general. And it could be a big impact since it involves the money that they used to pay for the upgrade.

At the same time, this gets "fixed" when the app is restarted, or the `Activity` is recreated. Or when they open the Upgrades screen again. 

Considering all of these, I think it's okay to move this to **Iteration 4**.
