### ISSUE TITLE
[Products list] "+" button disappears after pull to refresh

### ISSUE THREAD

**Issue by pachlava** [woocommerce/woocommerce-android#8600]
### Describe the bug
There are three cases (two for Products screen, one for Orders). Issue is titled by the most impactful one (IMO).

#### Case 1:
1. Open Products list
2. Pull to refresh ~> "+" disappears and does not reappear unless screen is reopened

https://user-images.githubusercontent.com/73365754/226398838-3843882f-7b87-42ac-974d-38dba83085c5.mp4

#### Case 2:
1. Open Products list
2. Open any product
3. Go back to list ~> "+" disappears and reappears after screen is touched

https://user-images.githubusercontent.com/73365754/226399872-f275e8fc-f078-4f1d-bad0-48efde3efd91.mp4

#### Case 3:
Same as Case 2, but for Products:

https://user-images.githubusercontent.com/73365754/226399994-84d1e943-f802-486a-b490-b953a00144c4.mp4

### Expected behaviour
If a screen (in given mode) contains "+" button, the button should be there always.

### Mobile Environment
- Device: Pixel 7 
- Android version: 13
- WooCommerce Android version: 12.8-rc-1

**Comment by shiki** [comment]
Internal ref peaMlT-45-p2. 

Caused by https://github.com/woocommerce/woocommerce-android/issues/7986.

**Comment by ThomazFB** [comment]
https://github.com/woocommerce/woocommerce-android/pull/8841 fixes the `Case 1` described in this issue. `Case 2` and `Case 3` seems to be a very different (and way more complex) issue not related with visibility control, but something going bad with our animated view transitions.

CC: @shiki

**Comment by shiki** [comment]
@ThomazFB When I check out 11.6 (d0ba05e598), everything seems to be working fine. 

https://user-images.githubusercontent.com/198826/232805908-03829064-ab77-4e79-8cb0-4830905224d1.mp4

I shared in peaMlT-45-p2#comment-213 that Case 1 was caused by https://github.com/woocommerce/woocommerce-android/issues/7986. What happens if we just revert that PR instead? Will it fix Case 2 and 3 too?

**Comment by ThomazFB** [comment]
Good point, @shiki. My approach was more based on the fact that we shouldn't animate stuff for situations where the UI state can change so fast. I'll try revert the changes before the `11.6` version you pointed out to see what happens, #7968 is a good candidate indeed because it affects fundamentally every single Fragment using the FAB, but I was looking to avoid reverting that because it could slow down the FAB back again.

Thanks!

**Comment by ThomazFB** [comment]
https://github.com/woocommerce/woocommerce-android/pull/8841 updated with changes reverting https://github.com/woocommerce/woocommerce-android/issues/7986 and trying a different approach for the laggy animation issue, which that PR was trying to fix.

I can confirm that the changes now fix all problems described in this issue.


CC: @shiki
