### ISSUE TITLE
If site is inaccessible after logging in - there's no way to log in as a different user.

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-android#954]
**Describe the bug**

Same issue with iOS: https://github.com/woocommerce/woocommerce-ios/issues/828

Basically if we log in and the sites are not accessible for some reason - it isn't possible to log out and log in as a different user which makes the troubleshooting workflow difficult (the only workaround is to re-install the app).

**To Reproduce**

1. Log in as a user with connection issues (one of examples - 1924167 zen)
2. It isn't possible to log in as a different user and we're "trapped" on site choice screen

**Expected behavior**

I'd hope to be able to log in as a different user if I'm unable to access a site as this particular user. Not sure if that's the best flow for regular users but this would definitely make troubleshooting easier as we wouldn't have to re-install the app to access a different account.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. Not applicable
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Mobile Environment**
Please include:
- Device: Android simulator
- Android version: 1.5-rc-2, also older versions
- WooCommerce Android version: 8

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by jkmassel** [comment]
This is being bumped to 1.7. If it needs to ship sooner, please merge it to release/1.6, and let me know when you're ready for a hotfix release!

**Comment by AmandaRiu** [comment]
@kyleaparker We have a "Login with a different account" option which is what currently shows when the user has **NO** stores for the current login. In this case, we have stores, but we cannot connect to them. I've been thinking about this and it seems to me we could _always_ show that button regardless of the status of stores because for users who have multiple WordPress.com accounts, they may see the available sites and _want_ to use a different login which currently we don't have an option for. I know I run into this scenario all the time. It seems in the current Zendesk ticket our user has a case for this as well. What do you think about just adding the "Login with a different account" button to the screen, maybe below or above "continue"? Maybe something like this:

<img src="https://user-images.githubusercontent.com/5810477/55818807-1ccc9880-5abd-11e9-9ecc-5091051c4c08.png" width="300"/>

Since this screen is used during login and site switching, it fits in both scenarios.

cc: @astralbodies @bummytime

**Comment by kyleaparker** [comment]
I think an additional button works for this case, but can we match this button style and update the copy to "Try another account":

<img width="668" alt="Sign In Flow 2019-04-11 13-00-29" src="https://user-images.githubusercontent.com/712873/55976323-e5472300-5c59-11e9-9c28-df315a88291d.png">

This problem was also explored in the upcoming sign in changes that make it easier to identify if the store is connected with the logged in account: 

<img width="409" alt="Sign In Flow 2019-04-11 12-56-28" src="https://user-images.githubusercontent.com/712873/55976362-f728c600-5c59-11e9-9c68-d67b2ddba7cd.png">

**Comment by AmandaRiu** [comment]
Sign in milestone 1 is actively being developed and would alleviate this issue so I'm going to put this one on hold for the time being.

**Comment by AmandaRiu** [comment]
The new sign in has been implemented and this is still an issue since the actual store picker screen does not have the option enabled to "Try another account". That's an easy fix and we should add it. The "Try another account" should be a secondary action (white button)

![Screenshot_1562772664](https://user-images.githubusercontent.com/5810477/60982617-b8a4b500-a2f5-11e9-9830-5ca222043637.png)

**Comment by AmandaRiu** [comment]
Updated designs have been posted so I'll be getting this fix implemented:

<img width="384" alt="sign-in-flow-2019-08-15-12-24-07" src="https://user-images.githubusercontent.com/5810477/63397740-6b9a1100-c380-11e9-83be-913e9237fb63.png">
